/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * AgreementLinks
 * 
 * <p>Hypermedia controls (HATEOAS) for agreement specific links to resources.
 */
public class AgreementLinks {
    /**
     * A URL that references a specific resource.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("document")
    private JsonNullable<? extends Link> document;

    @JsonCreator
    public AgreementLinks(
            @JsonProperty("document") JsonNullable<? extends Link> document) {
        Utils.checkNotNull(document, "document");
        this.document = document;
    }
    
    public AgreementLinks() {
        this(JsonNullable.undefined());
    }

    /**
     * A URL that references a specific resource.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<Link> document() {
        return (JsonNullable<Link>) document;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * A URL that references a specific resource.
     */
    public AgreementLinks withDocument(Link document) {
        Utils.checkNotNull(document, "document");
        this.document = JsonNullable.of(document);
        return this;
    }

    /**
     * A URL that references a specific resource.
     */
    public AgreementLinks withDocument(JsonNullable<? extends Link> document) {
        Utils.checkNotNull(document, "document");
        this.document = document;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        AgreementLinks other = (AgreementLinks) o;
        return 
            Utils.enhancedDeepEquals(this.document, other.document);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            document);
    }
    
    @Override
    public String toString() {
        return Utils.toString(AgreementLinks.class,
                "document", document);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<? extends Link> document = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * A URL that references a specific resource.
         */
        public Builder document(Link document) {
            Utils.checkNotNull(document, "document");
            this.document = JsonNullable.of(document);
            return this;
        }

        /**
         * A URL that references a specific resource.
         */
        public Builder document(JsonNullable<? extends Link> document) {
            Utils.checkNotNull(document, "document");
            this.document = document;
            return this;
        }

        public AgreementLinks build() {

            return new AgreementLinks(
                document);
        }

    }
}
