/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * BulkJobConstraints
 * 
 * <p>Describes the limits of a bulk job, or an action associated with a bulk job
 */
public class BulkJobConstraints {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("allowed_formats")
    private Optional<? extends List<String>> allowedFormats;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max_documents_per_job")
    private Optional<Integer> maxDocumentsPerJob;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("max_size_mb")
    private Optional<Integer> maxSizeMb;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("timeout_seconds")
    private Optional<Integer> timeoutSeconds;

    @JsonCreator
    public BulkJobConstraints(
            @JsonProperty("allowed_formats") Optional<? extends List<String>> allowedFormats,
            @JsonProperty("max_documents_per_job") Optional<Integer> maxDocumentsPerJob,
            @JsonProperty("max_size_mb") Optional<Integer> maxSizeMb,
            @JsonProperty("timeout_seconds") Optional<Integer> timeoutSeconds) {
        Utils.checkNotNull(allowedFormats, "allowedFormats");
        Utils.checkNotNull(maxDocumentsPerJob, "maxDocumentsPerJob");
        Utils.checkNotNull(maxSizeMb, "maxSizeMb");
        Utils.checkNotNull(timeoutSeconds, "timeoutSeconds");
        this.allowedFormats = allowedFormats;
        this.maxDocumentsPerJob = maxDocumentsPerJob;
        this.maxSizeMb = maxSizeMb;
        this.timeoutSeconds = timeoutSeconds;
    }
    
    public BulkJobConstraints() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<String>> allowedFormats() {
        return (Optional<List<String>>) allowedFormats;
    }

    @JsonIgnore
    public Optional<Integer> maxDocumentsPerJob() {
        return maxDocumentsPerJob;
    }

    @JsonIgnore
    public Optional<Integer> maxSizeMb() {
        return maxSizeMb;
    }

    @JsonIgnore
    public Optional<Integer> timeoutSeconds() {
        return timeoutSeconds;
    }

    public static Builder builder() {
        return new Builder();
    }


    public BulkJobConstraints withAllowedFormats(List<String> allowedFormats) {
        Utils.checkNotNull(allowedFormats, "allowedFormats");
        this.allowedFormats = Optional.ofNullable(allowedFormats);
        return this;
    }


    public BulkJobConstraints withAllowedFormats(Optional<? extends List<String>> allowedFormats) {
        Utils.checkNotNull(allowedFormats, "allowedFormats");
        this.allowedFormats = allowedFormats;
        return this;
    }

    public BulkJobConstraints withMaxDocumentsPerJob(int maxDocumentsPerJob) {
        Utils.checkNotNull(maxDocumentsPerJob, "maxDocumentsPerJob");
        this.maxDocumentsPerJob = Optional.ofNullable(maxDocumentsPerJob);
        return this;
    }


    public BulkJobConstraints withMaxDocumentsPerJob(Optional<Integer> maxDocumentsPerJob) {
        Utils.checkNotNull(maxDocumentsPerJob, "maxDocumentsPerJob");
        this.maxDocumentsPerJob = maxDocumentsPerJob;
        return this;
    }

    public BulkJobConstraints withMaxSizeMb(int maxSizeMb) {
        Utils.checkNotNull(maxSizeMb, "maxSizeMb");
        this.maxSizeMb = Optional.ofNullable(maxSizeMb);
        return this;
    }


    public BulkJobConstraints withMaxSizeMb(Optional<Integer> maxSizeMb) {
        Utils.checkNotNull(maxSizeMb, "maxSizeMb");
        this.maxSizeMb = maxSizeMb;
        return this;
    }

    public BulkJobConstraints withTimeoutSeconds(int timeoutSeconds) {
        Utils.checkNotNull(timeoutSeconds, "timeoutSeconds");
        this.timeoutSeconds = Optional.ofNullable(timeoutSeconds);
        return this;
    }


    public BulkJobConstraints withTimeoutSeconds(Optional<Integer> timeoutSeconds) {
        Utils.checkNotNull(timeoutSeconds, "timeoutSeconds");
        this.timeoutSeconds = timeoutSeconds;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BulkJobConstraints other = (BulkJobConstraints) o;
        return 
            Utils.enhancedDeepEquals(this.allowedFormats, other.allowedFormats) &&
            Utils.enhancedDeepEquals(this.maxDocumentsPerJob, other.maxDocumentsPerJob) &&
            Utils.enhancedDeepEquals(this.maxSizeMb, other.maxSizeMb) &&
            Utils.enhancedDeepEquals(this.timeoutSeconds, other.timeoutSeconds);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            allowedFormats, maxDocumentsPerJob, maxSizeMb,
            timeoutSeconds);
    }
    
    @Override
    public String toString() {
        return Utils.toString(BulkJobConstraints.class,
                "allowedFormats", allowedFormats,
                "maxDocumentsPerJob", maxDocumentsPerJob,
                "maxSizeMb", maxSizeMb,
                "timeoutSeconds", timeoutSeconds);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<String>> allowedFormats = Optional.empty();

        private Optional<Integer> maxDocumentsPerJob = Optional.empty();

        private Optional<Integer> maxSizeMb = Optional.empty();

        private Optional<Integer> timeoutSeconds = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder allowedFormats(List<String> allowedFormats) {
            Utils.checkNotNull(allowedFormats, "allowedFormats");
            this.allowedFormats = Optional.ofNullable(allowedFormats);
            return this;
        }

        public Builder allowedFormats(Optional<? extends List<String>> allowedFormats) {
            Utils.checkNotNull(allowedFormats, "allowedFormats");
            this.allowedFormats = allowedFormats;
            return this;
        }


        public Builder maxDocumentsPerJob(int maxDocumentsPerJob) {
            Utils.checkNotNull(maxDocumentsPerJob, "maxDocumentsPerJob");
            this.maxDocumentsPerJob = Optional.ofNullable(maxDocumentsPerJob);
            return this;
        }

        public Builder maxDocumentsPerJob(Optional<Integer> maxDocumentsPerJob) {
            Utils.checkNotNull(maxDocumentsPerJob, "maxDocumentsPerJob");
            this.maxDocumentsPerJob = maxDocumentsPerJob;
            return this;
        }


        public Builder maxSizeMb(int maxSizeMb) {
            Utils.checkNotNull(maxSizeMb, "maxSizeMb");
            this.maxSizeMb = Optional.ofNullable(maxSizeMb);
            return this;
        }

        public Builder maxSizeMb(Optional<Integer> maxSizeMb) {
            Utils.checkNotNull(maxSizeMb, "maxSizeMb");
            this.maxSizeMb = maxSizeMb;
            return this;
        }


        public Builder timeoutSeconds(int timeoutSeconds) {
            Utils.checkNotNull(timeoutSeconds, "timeoutSeconds");
            this.timeoutSeconds = Optional.ofNullable(timeoutSeconds);
            return this;
        }

        public Builder timeoutSeconds(Optional<Integer> timeoutSeconds) {
            Utils.checkNotNull(timeoutSeconds, "timeoutSeconds");
            this.timeoutSeconds = timeoutSeconds;
            return this;
        }

        public BulkJobConstraints build() {

            return new BulkJobConstraints(
                allowedFormats, maxDocumentsPerJob, maxSizeMb,
                timeoutSeconds);
        }

    }
}
