/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;


public class CreateWorkspaceEnvelopeResponse {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("envelope_id")
    private JsonNullable<String> envelopeId;

    @JsonCreator
    public CreateWorkspaceEnvelopeResponse(
            @JsonProperty("envelope_id") JsonNullable<String> envelopeId) {
        Utils.checkNotNull(envelopeId, "envelopeId");
        this.envelopeId = envelopeId;
    }
    
    public CreateWorkspaceEnvelopeResponse() {
        this(JsonNullable.undefined());
    }

    @JsonIgnore
    public JsonNullable<String> envelopeId() {
        return envelopeId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CreateWorkspaceEnvelopeResponse withEnvelopeId(String envelopeId) {
        Utils.checkNotNull(envelopeId, "envelopeId");
        this.envelopeId = JsonNullable.of(envelopeId);
        return this;
    }

    public CreateWorkspaceEnvelopeResponse withEnvelopeId(JsonNullable<String> envelopeId) {
        Utils.checkNotNull(envelopeId, "envelopeId");
        this.envelopeId = envelopeId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateWorkspaceEnvelopeResponse other = (CreateWorkspaceEnvelopeResponse) o;
        return 
            Utils.enhancedDeepEquals(this.envelopeId, other.envelopeId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            envelopeId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateWorkspaceEnvelopeResponse.class,
                "envelopeId", envelopeId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> envelopeId = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder envelopeId(String envelopeId) {
            Utils.checkNotNull(envelopeId, "envelopeId");
            this.envelopeId = JsonNullable.of(envelopeId);
            return this;
        }

        public Builder envelopeId(JsonNullable<String> envelopeId) {
            Utils.checkNotNull(envelopeId, "envelopeId");
            this.envelopeId = envelopeId;
            return this;
        }

        public CreateWorkspaceEnvelopeResponse build() {

            return new CreateWorkspaceEnvelopeResponse(
                envelopeId);
        }

    }
}
