/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class CreateWorkspaceBody {
    /**
     * The name of the workspace
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("name")
    private Optional<String> name;

    /**
     * A GUID value that identifies a brand. For more information, see <a
     * href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("brand_id")
    private JsonNullable<String> brandId;

    @JsonCreator
    public CreateWorkspaceBody(
            @JsonProperty("name") Optional<String> name,
            @JsonProperty("brand_id") JsonNullable<String> brandId) {
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(brandId, "brandId");
        this.name = name;
        this.brandId = brandId;
    }
    
    public CreateWorkspaceBody() {
        this(Optional.empty(), JsonNullable.undefined());
    }

    /**
     * The name of the workspace
     */
    @JsonIgnore
    public Optional<String> name() {
        return name;
    }

    /**
     * A GUID value that identifies a brand. For more information, see <a
     * href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
     */
    @JsonIgnore
    public JsonNullable<String> brandId() {
        return brandId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The name of the workspace
     */
    public CreateWorkspaceBody withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = Optional.ofNullable(name);
        return this;
    }


    /**
     * The name of the workspace
     */
    public CreateWorkspaceBody withName(Optional<String> name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    /**
     * A GUID value that identifies a brand. For more information, see <a
     * href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
     */
    public CreateWorkspaceBody withBrandId(String brandId) {
        Utils.checkNotNull(brandId, "brandId");
        this.brandId = JsonNullable.of(brandId);
        return this;
    }

    /**
     * A GUID value that identifies a brand. For more information, see <a
     * href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
     */
    public CreateWorkspaceBody withBrandId(JsonNullable<String> brandId) {
        Utils.checkNotNull(brandId, "brandId");
        this.brandId = brandId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateWorkspaceBody other = (CreateWorkspaceBody) o;
        return 
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.brandId, other.brandId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            name, brandId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateWorkspaceBody.class,
                "name", name,
                "brandId", brandId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> name = Optional.empty();

        private JsonNullable<String> brandId = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The name of the workspace
         */
        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * The name of the workspace
         */
        public Builder name(Optional<String> name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        /**
         * A GUID value that identifies a brand. For more information, see <a
         * href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
         */
        public Builder brandId(String brandId) {
            Utils.checkNotNull(brandId, "brandId");
            this.brandId = JsonNullable.of(brandId);
            return this;
        }

        /**
         * A GUID value that identifies a brand. For more information, see <a
         * href="https://developers.docusign.com/docs/esign-rest-api/esign101/concepts/branding/">Branding</a>
         */
        public Builder brandId(JsonNullable<String> brandId) {
            Utils.checkNotNull(brandId, "brandId");
            this.brandId = brandId;
            return this;
        }

        public CreateWorkspaceBody build() {

            return new CreateWorkspaceBody(
                name, brandId);
        }

    }
}
