/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.OneOfDeserializer;
import com.docusign.iam.sdk.utils.TypedObject;
import com.docusign.iam.sdk.utils.Utils.JsonShape;
import com.docusign.iam.sdk.utils.Utils.TypeReferenceWithShape;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * DefaultValue
 * 
 * <p>The default value for the input field if one is provided. This can be a string, number,
 * boolean, object, or array. If no value is provided during the trigger, the workflow may
 * use this default value.
 */
@JsonDeserialize(using = DefaultValue._Deserializer.class)
public class DefaultValue {

    @JsonValue
    private TypedObject value;
    
    private DefaultValue(TypedObject value) {
        this.value = value;
    }

    public static DefaultValue of(String value) {
        Utils.checkNotNull(value, "value");
        return new DefaultValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<String>(){}));
    }

    public static DefaultValue of(double value) {
        Utils.checkNotNull(value, "value");
        return new DefaultValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<java.lang.Double>(){}));
    }

    public static DefaultValue of(boolean value) {
        Utils.checkNotNull(value, "value");
        return new DefaultValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<java.lang.Boolean>(){}));
    }

    public static DefaultValue of(Map<String, Object> value) {
        Utils.checkNotNull(value, "value");
        return new DefaultValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<Map<String, Object>>(){}));
    }

    public static DefaultValue of(List<Object> value) {
        Utils.checkNotNull(value, "value");
        return new DefaultValue(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<List<Object>>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code java.lang.String}</li>
     * <li>{@code double}</li>
     * <li>{@code boolean}</li>
     * <li>{@code java.util.Map<java.lang.String, java.lang.Object>}</li>
     * <li>{@code java.util.List<java.lang.Object>}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DefaultValue other = (DefaultValue) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<DefaultValue> {

        public _Deserializer() {
            super(DefaultValue.class, false,
                  TypeReferenceWithShape.of(new TypeReference<List<Object>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Map<String, Object>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Boolean>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<Double>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<String>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(DefaultValue.class,
                "value", value);
    }
 
}

