/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

/**
 * GetWorkspaceUploadRequestsResponse
 * 
 * <p>Response containing a list of upload requests
 */
public class GetWorkspaceUploadRequestsResponse {
    /**
     * The upload request list
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("data")
    private Optional<? extends List<WorkspaceUploadRequest>> data;

    @JsonCreator
    public GetWorkspaceUploadRequestsResponse(
            @JsonProperty("data") Optional<? extends List<WorkspaceUploadRequest>> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
    }
    
    public GetWorkspaceUploadRequestsResponse() {
        this(Optional.empty());
    }

    /**
     * The upload request list
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<WorkspaceUploadRequest>> data() {
        return (Optional<List<WorkspaceUploadRequest>>) data;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The upload request list
     */
    public GetWorkspaceUploadRequestsResponse withData(List<WorkspaceUploadRequest> data) {
        Utils.checkNotNull(data, "data");
        this.data = Optional.ofNullable(data);
        return this;
    }


    /**
     * The upload request list
     */
    public GetWorkspaceUploadRequestsResponse withData(Optional<? extends List<WorkspaceUploadRequest>> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceUploadRequestsResponse other = (GetWorkspaceUploadRequestsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceUploadRequestsResponse.class,
                "data", data);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends List<WorkspaceUploadRequest>> data = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The upload request list
         */
        public Builder data(List<WorkspaceUploadRequest> data) {
            Utils.checkNotNull(data, "data");
            this.data = Optional.ofNullable(data);
            return this;
        }

        /**
         * The upload request list
         */
        public Builder data(Optional<? extends List<WorkspaceUploadRequest>> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }

        public GetWorkspaceUploadRequestsResponse build() {

            return new GetWorkspaceUploadRequestsResponse(
                data);
        }

    }
}
