/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;


public class JWTGrantResponse {
    /**
     * The value of the access token. This value will be added to the Authorization header of all Docusign API calls.
     */
    @JsonProperty("access_token")
    private String accessToken;

    /**
     * The type of token. For access tokens, the value of this will be Bearer.
     */
    @JsonProperty("token_type")
    private String tokenType;

    /**
     * The number of seconds until the access token expires.
     */
    @JsonProperty("expires_in")
    private long expiresIn;

    @JsonCreator
    public JWTGrantResponse(
            @JsonProperty("access_token") String accessToken,
            @JsonProperty("token_type") String tokenType,
            @JsonProperty("expires_in") long expiresIn) {
        Utils.checkNotNull(accessToken, "accessToken");
        Utils.checkNotNull(tokenType, "tokenType");
        Utils.checkNotNull(expiresIn, "expiresIn");
        this.accessToken = accessToken;
        this.tokenType = tokenType;
        this.expiresIn = expiresIn;
    }

    /**
     * The value of the access token. This value will be added to the Authorization header of all Docusign API calls.
     */
    @JsonIgnore
    public String accessToken() {
        return accessToken;
    }

    /**
     * The type of token. For access tokens, the value of this will be Bearer.
     */
    @JsonIgnore
    public String tokenType() {
        return tokenType;
    }

    /**
     * The number of seconds until the access token expires.
     */
    @JsonIgnore
    public long expiresIn() {
        return expiresIn;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The value of the access token. This value will be added to the Authorization header of all Docusign API calls.
     */
    public JWTGrantResponse withAccessToken(String accessToken) {
        Utils.checkNotNull(accessToken, "accessToken");
        this.accessToken = accessToken;
        return this;
    }

    /**
     * The type of token. For access tokens, the value of this will be Bearer.
     */
    public JWTGrantResponse withTokenType(String tokenType) {
        Utils.checkNotNull(tokenType, "tokenType");
        this.tokenType = tokenType;
        return this;
    }

    /**
     * The number of seconds until the access token expires.
     */
    public JWTGrantResponse withExpiresIn(long expiresIn) {
        Utils.checkNotNull(expiresIn, "expiresIn");
        this.expiresIn = expiresIn;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JWTGrantResponse other = (JWTGrantResponse) o;
        return 
            Utils.enhancedDeepEquals(this.accessToken, other.accessToken) &&
            Utils.enhancedDeepEquals(this.tokenType, other.tokenType) &&
            Utils.enhancedDeepEquals(this.expiresIn, other.expiresIn);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accessToken, tokenType, expiresIn);
    }
    
    @Override
    public String toString() {
        return Utils.toString(JWTGrantResponse.class,
                "accessToken", accessToken,
                "tokenType", tokenType,
                "expiresIn", expiresIn);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accessToken;

        private String tokenType;

        private Long expiresIn;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The value of the access token. This value will be added to the Authorization header of all Docusign API calls.
         */
        public Builder accessToken(String accessToken) {
            Utils.checkNotNull(accessToken, "accessToken");
            this.accessToken = accessToken;
            return this;
        }


        /**
         * The type of token. For access tokens, the value of this will be Bearer.
         */
        public Builder tokenType(String tokenType) {
            Utils.checkNotNull(tokenType, "tokenType");
            this.tokenType = tokenType;
            return this;
        }


        /**
         * The number of seconds until the access token expires.
         */
        public Builder expiresIn(long expiresIn) {
            Utils.checkNotNull(expiresIn, "expiresIn");
            this.expiresIn = expiresIn;
            return this;
        }

        public JWTGrantResponse build() {

            return new JWTGrantResponse(
                accessToken, tokenType, expiresIn);
        }

    }
}
