/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * Method
 * 
 * <p>The HTTP method used to trigger the workflow. This defines the type of request
 * that will initiate the workflow (e.g., GET, POST).
 */
public enum Method {
    GET("GET"),
    POST("POST"),
    PUT("PUT"),
    PATCH("PATCH"),
    DELETE("DELETE");

    @JsonValue
    private final String value;

    Method(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<Method> fromValue(String value) {
        for (Method o: Method.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

