/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;

/**
 * PauseNewWorkflowInstancesSuccess
 * 
 * <p>Indicates that a workflow has been successfully paused. New instances of this workflow will not be created.
 * Existing workflow instances will be unaffected.
 */
public class PauseNewWorkflowInstancesSuccess {

    /**
     * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
     * Valid values include:
     * 
     * <p>  - active
     *   - paused
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status")
    private Optional<String> status;

    @JsonCreator
    public PauseNewWorkflowInstancesSuccess(
            @JsonProperty("status") Optional<String> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
    }
    
    public PauseNewWorkflowInstancesSuccess() {
        this(Optional.empty());
    }

    /**
     * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
     * Valid values include:
     * 
     * <p>  - active
     *   - paused
     */
    @JsonIgnore
    public Optional<String> status() {
        return status;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
     * Valid values include:
     * 
     * <p>  - active
     *   - paused
     */
    public PauseNewWorkflowInstancesSuccess withStatus(String status) {
        Utils.checkNotNull(status, "status");
        this.status = Optional.ofNullable(status);
        return this;
    }

    /**
     * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
     * Valid values include:
     * 
     * <p>  - active
     *   - paused
     */
    public PauseNewWorkflowInstancesSuccess withStatus(Optional<String> status) {
        Utils.checkNotNull(status, "status");
        this.status = status;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PauseNewWorkflowInstancesSuccess other = (PauseNewWorkflowInstancesSuccess) o;
        return 
            Utils.enhancedDeepEquals(this.status, other.status);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            status);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PauseNewWorkflowInstancesSuccess.class,
                "status", status);
    }
    
    public final static class Builder {
 
        private Optional<String> status = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
         * Valid values include:
         * 
         * <p>  - active
         *   - paused
         */
        public Builder status(String status) {
            Utils.checkNotNull(status, "status");
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * Represents the new state of a workflow's mechanism to permit new workflow instances from being created.
         * Valid values include:
         * 
         * <p>  - active
         *   - paused
         */
        public Builder status(Optional<String> status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }
        
        public PauseNewWorkflowInstancesSuccess build() {
            return new PauseNewWorkflowInstancesSuccess(
                status);
        }
    }
}
