/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.LazySingletonValue;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Boolean;
import java.lang.Double;
import java.lang.Float;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * Provisions
 * 
 * <p>"The conditions or rules written in a legal agreement. The set of possible provisions is determined
 * by the agreement type."
 */
public class Provisions {
    /**
     * Provisions related to changes in control of the assigning party
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("assignment_change_of_control")
    private JsonNullable<String> assignmentChangeOfControl;

    /**
     * Provisions for the termination of assignment rights
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("assignment_termination_rights")
    private JsonNullable<String> assignmentTerminationRights;

    /**
     * The type of assignment rights in the agreement (e.g., transferability)
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("assignment_type")
    private JsonNullable<String> assignmentType;

    /**
     * A subset of ISO 8601 duration. Fractional or negative values are not supported.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("confidentiality_obligation_period")
    private JsonNullable<String> confidentialityObligationPeriod;

    /**
     * The governing law clause identifies the substantive law that will govern the rights and obligations
     * of the parties to the agreement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("governing_law")
    private JsonNullable<String> governingLaw;

    /**
     * A jurisdiction clause expressly sets out which courts or tribunals have the power to hear a dispute
     * which arises under the agreement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("jurisdiction")
    private JsonNullable<String> jurisdiction;

    /**
     * Type of non-disclosure agreement (e.g., unilateral, bilateral).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("nda_type")
    private JsonNullable<String> ndaType;

    /**
     * Total annual value of the agreement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("annual_agreement_value")
    private JsonNullable<Double> annualAgreementValue;

    /**
     * Currency code (e.g., USD, EUR) for the agreement's annual value.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("annual_agreement_value_currency_code")
    private JsonNullable<? extends CurrencyCode> annualAgreementValueCurrencyCode;

    /**
     * Total value of the agreement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("total_agreement_value")
    private JsonNullable<Double> totalAgreementValue;

    /**
     * Currency code (e.g., USD, EUR) for the agreement's total value.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("total_agreement_value_currency_code")
    private JsonNullable<? extends CurrencyCode> totalAgreementValueCurrencyCode;

    /**
     * Terms specifying the payment due date, based on a defined number of days or other conditions.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_terms_due_date")
    private Optional<? extends PaymentTermsDueDate> paymentTermsDueDate;

    /**
     * Indicates if late payment fees can be charged.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("can_charge_late_payment_fees")
    private JsonNullable<Boolean> canChargeLatePaymentFees;

    /**
     * Percentage fee charged on late payments.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("late_payment_fee_percent")
    private JsonNullable<Double> latePaymentFeePercent;

    /**
     * Currency code for the liability cap amount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("liability_cap_currency_code")
    private JsonNullable<? extends CurrencyCode> liabilityCapCurrencyCode;

    /**
     * Duration for the liability cap
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("liability_cap_duration")
    private JsonNullable<String> liabilityCapDuration;

    /**
     * Maximum liability cap in the agreement
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("liability_cap_fixed_amount")
    private JsonNullable<Double> liabilityCapFixedAmount;

    /**
     * Multiplier applied to calculate the liability cap
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("liability_cap_multiplier")
    private JsonNullable<Double> liabilityCapMultiplier;

    /**
     * Maximum allowed percentage increase in prices, limited between 0 and 100.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("price_cap_percent_increase")
    private JsonNullable<Float> priceCapPercentIncrease;

    /**
     * The duration of the auto-renewal period.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("auto_renewal_term_length")
    private JsonNullable<String> autoRenewalTermLength;

    /**
     * Additional information related to the renewal process.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_additional_info")
    private JsonNullable<String> renewalAdditionalInfo;

    /**
     * The period an agreement has been extended after it has been renewed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_extension_period")
    private JsonNullable<String> renewalExtensionPeriod;

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_notice_date")
    private Optional<String> renewalNoticeDate;

    /**
     * The period of time that a party is required to provide to indicate their intention to renew an
     * agreement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_notice_period")
    private JsonNullable<String> renewalNoticePeriod;

    /**
     * User ID of the person responsible for managing the renewal process
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_process_owner")
    private Optional<String> renewalProcessOwner;

    /**
     * Specifies the type of renewal (e.g., automatic, manual).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("renewal_type")
    private JsonNullable<String> renewalType;

    /**
     * The specific duration that a party has to give notice before terminating the agreement due to a
     * significant breach or violation of terms.
     * This period allows the other party to address the cause or prepare for termination.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("termination_period_for_cause")
    private JsonNullable<String> terminationPeriodForCause;

    /**
     * Specifies the required notice period that a party must provide before terminating the agreement for
     * convenience, without cause, under the terms outlined in the contract.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("termination_period_for_convenience")
    private JsonNullable<String> terminationPeriodForConvenience;

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("effective_date")
    private Optional<String> effectiveDate;

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("execution_date")
    private Optional<String> executionDate;

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expiration_date")
    private Optional<String> expirationDate;

    /**
     * Overall duration of the agreement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("term_length")
    private JsonNullable<String> termLength;

    @JsonCreator
    public Provisions(
            @JsonProperty("assignment_change_of_control") JsonNullable<String> assignmentChangeOfControl,
            @JsonProperty("assignment_termination_rights") JsonNullable<String> assignmentTerminationRights,
            @JsonProperty("assignment_type") JsonNullable<String> assignmentType,
            @JsonProperty("confidentiality_obligation_period") JsonNullable<String> confidentialityObligationPeriod,
            @JsonProperty("governing_law") JsonNullable<String> governingLaw,
            @JsonProperty("jurisdiction") JsonNullable<String> jurisdiction,
            @JsonProperty("nda_type") JsonNullable<String> ndaType,
            @JsonProperty("annual_agreement_value") JsonNullable<Double> annualAgreementValue,
            @JsonProperty("annual_agreement_value_currency_code") JsonNullable<? extends CurrencyCode> annualAgreementValueCurrencyCode,
            @JsonProperty("total_agreement_value") JsonNullable<Double> totalAgreementValue,
            @JsonProperty("total_agreement_value_currency_code") JsonNullable<? extends CurrencyCode> totalAgreementValueCurrencyCode,
            @JsonProperty("payment_terms_due_date") Optional<? extends PaymentTermsDueDate> paymentTermsDueDate,
            @JsonProperty("can_charge_late_payment_fees") JsonNullable<Boolean> canChargeLatePaymentFees,
            @JsonProperty("late_payment_fee_percent") JsonNullable<Double> latePaymentFeePercent,
            @JsonProperty("liability_cap_currency_code") JsonNullable<? extends CurrencyCode> liabilityCapCurrencyCode,
            @JsonProperty("liability_cap_duration") JsonNullable<String> liabilityCapDuration,
            @JsonProperty("liability_cap_fixed_amount") JsonNullable<Double> liabilityCapFixedAmount,
            @JsonProperty("liability_cap_multiplier") JsonNullable<Double> liabilityCapMultiplier,
            @JsonProperty("price_cap_percent_increase") JsonNullable<Float> priceCapPercentIncrease,
            @JsonProperty("auto_renewal_term_length") JsonNullable<String> autoRenewalTermLength,
            @JsonProperty("renewal_additional_info") JsonNullable<String> renewalAdditionalInfo,
            @JsonProperty("renewal_extension_period") JsonNullable<String> renewalExtensionPeriod,
            @JsonProperty("renewal_notice_date") Optional<String> renewalNoticeDate,
            @JsonProperty("renewal_notice_period") JsonNullable<String> renewalNoticePeriod,
            @JsonProperty("renewal_process_owner") Optional<String> renewalProcessOwner,
            @JsonProperty("renewal_type") JsonNullable<String> renewalType,
            @JsonProperty("termination_period_for_cause") JsonNullable<String> terminationPeriodForCause,
            @JsonProperty("termination_period_for_convenience") JsonNullable<String> terminationPeriodForConvenience,
            @JsonProperty("effective_date") Optional<String> effectiveDate,
            @JsonProperty("execution_date") Optional<String> executionDate,
            @JsonProperty("expiration_date") Optional<String> expirationDate,
            @JsonProperty("term_length") JsonNullable<String> termLength) {
        Utils.checkNotNull(assignmentChangeOfControl, "assignmentChangeOfControl");
        Utils.checkNotNull(assignmentTerminationRights, "assignmentTerminationRights");
        Utils.checkNotNull(assignmentType, "assignmentType");
        Utils.checkNotNull(confidentialityObligationPeriod, "confidentialityObligationPeriod");
        Utils.checkNotNull(governingLaw, "governingLaw");
        Utils.checkNotNull(jurisdiction, "jurisdiction");
        Utils.checkNotNull(ndaType, "ndaType");
        Utils.checkNotNull(annualAgreementValue, "annualAgreementValue");
        Utils.checkNotNull(annualAgreementValueCurrencyCode, "annualAgreementValueCurrencyCode");
        Utils.checkNotNull(totalAgreementValue, "totalAgreementValue");
        Utils.checkNotNull(totalAgreementValueCurrencyCode, "totalAgreementValueCurrencyCode");
        Utils.checkNotNull(paymentTermsDueDate, "paymentTermsDueDate");
        Utils.checkNotNull(canChargeLatePaymentFees, "canChargeLatePaymentFees");
        Utils.checkNotNull(latePaymentFeePercent, "latePaymentFeePercent");
        Utils.checkNotNull(liabilityCapCurrencyCode, "liabilityCapCurrencyCode");
        Utils.checkNotNull(liabilityCapDuration, "liabilityCapDuration");
        Utils.checkNotNull(liabilityCapFixedAmount, "liabilityCapFixedAmount");
        Utils.checkNotNull(liabilityCapMultiplier, "liabilityCapMultiplier");
        Utils.checkNotNull(priceCapPercentIncrease, "priceCapPercentIncrease");
        Utils.checkNotNull(autoRenewalTermLength, "autoRenewalTermLength");
        Utils.checkNotNull(renewalAdditionalInfo, "renewalAdditionalInfo");
        Utils.checkNotNull(renewalExtensionPeriod, "renewalExtensionPeriod");
        Utils.checkNotNull(renewalNoticeDate, "renewalNoticeDate");
        Utils.checkNotNull(renewalNoticePeriod, "renewalNoticePeriod");
        Utils.checkNotNull(renewalProcessOwner, "renewalProcessOwner");
        Utils.checkNotNull(renewalType, "renewalType");
        Utils.checkNotNull(terminationPeriodForCause, "terminationPeriodForCause");
        Utils.checkNotNull(terminationPeriodForConvenience, "terminationPeriodForConvenience");
        Utils.checkNotNull(effectiveDate, "effectiveDate");
        Utils.checkNotNull(executionDate, "executionDate");
        Utils.checkNotNull(expirationDate, "expirationDate");
        Utils.checkNotNull(termLength, "termLength");
        this.assignmentChangeOfControl = assignmentChangeOfControl;
        this.assignmentTerminationRights = assignmentTerminationRights;
        this.assignmentType = assignmentType;
        this.confidentialityObligationPeriod = confidentialityObligationPeriod;
        this.governingLaw = governingLaw;
        this.jurisdiction = jurisdiction;
        this.ndaType = ndaType;
        this.annualAgreementValue = annualAgreementValue;
        this.annualAgreementValueCurrencyCode = annualAgreementValueCurrencyCode;
        this.totalAgreementValue = totalAgreementValue;
        this.totalAgreementValueCurrencyCode = totalAgreementValueCurrencyCode;
        this.paymentTermsDueDate = paymentTermsDueDate;
        this.canChargeLatePaymentFees = canChargeLatePaymentFees;
        this.latePaymentFeePercent = latePaymentFeePercent;
        this.liabilityCapCurrencyCode = liabilityCapCurrencyCode;
        this.liabilityCapDuration = liabilityCapDuration;
        this.liabilityCapFixedAmount = liabilityCapFixedAmount;
        this.liabilityCapMultiplier = liabilityCapMultiplier;
        this.priceCapPercentIncrease = priceCapPercentIncrease;
        this.autoRenewalTermLength = autoRenewalTermLength;
        this.renewalAdditionalInfo = renewalAdditionalInfo;
        this.renewalExtensionPeriod = renewalExtensionPeriod;
        this.renewalNoticeDate = renewalNoticeDate;
        this.renewalNoticePeriod = renewalNoticePeriod;
        this.renewalProcessOwner = renewalProcessOwner;
        this.renewalType = renewalType;
        this.terminationPeriodForCause = terminationPeriodForCause;
        this.terminationPeriodForConvenience = terminationPeriodForConvenience;
        this.effectiveDate = effectiveDate;
        this.executionDate = executionDate;
        this.expirationDate = expirationDate;
        this.termLength = termLength;
    }
    
    public Provisions() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), Optional.empty(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), Optional.empty(), JsonNullable.undefined(),
            Optional.empty(), JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), Optional.empty(), Optional.empty(),
            Optional.empty(), JsonNullable.undefined());
    }

    /**
     * Provisions related to changes in control of the assigning party
     */
    @JsonIgnore
    public JsonNullable<String> assignmentChangeOfControl() {
        return assignmentChangeOfControl;
    }

    /**
     * Provisions for the termination of assignment rights
     */
    @JsonIgnore
    public JsonNullable<String> assignmentTerminationRights() {
        return assignmentTerminationRights;
    }

    /**
     * The type of assignment rights in the agreement (e.g., transferability)
     */
    @JsonIgnore
    public JsonNullable<String> assignmentType() {
        return assignmentType;
    }

    /**
     * A subset of ISO 8601 duration. Fractional or negative values are not supported.
     */
    @JsonIgnore
    public JsonNullable<String> confidentialityObligationPeriod() {
        return confidentialityObligationPeriod;
    }

    /**
     * The governing law clause identifies the substantive law that will govern the rights and obligations
     * of the parties to the agreement.
     */
    @JsonIgnore
    public JsonNullable<String> governingLaw() {
        return governingLaw;
    }

    /**
     * A jurisdiction clause expressly sets out which courts or tribunals have the power to hear a dispute
     * which arises under the agreement.
     */
    @JsonIgnore
    public JsonNullable<String> jurisdiction() {
        return jurisdiction;
    }

    /**
     * Type of non-disclosure agreement (e.g., unilateral, bilateral).
     */
    @JsonIgnore
    public JsonNullable<String> ndaType() {
        return ndaType;
    }

    /**
     * Total annual value of the agreement.
     */
    @JsonIgnore
    public JsonNullable<Double> annualAgreementValue() {
        return annualAgreementValue;
    }

    /**
     * Currency code (e.g., USD, EUR) for the agreement's annual value.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<CurrencyCode> annualAgreementValueCurrencyCode() {
        return (JsonNullable<CurrencyCode>) annualAgreementValueCurrencyCode;
    }

    /**
     * Total value of the agreement.
     */
    @JsonIgnore
    public JsonNullable<Double> totalAgreementValue() {
        return totalAgreementValue;
    }

    /**
     * Currency code (e.g., USD, EUR) for the agreement's total value.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<CurrencyCode> totalAgreementValueCurrencyCode() {
        return (JsonNullable<CurrencyCode>) totalAgreementValueCurrencyCode;
    }

    /**
     * Terms specifying the payment due date, based on a defined number of days or other conditions.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaymentTermsDueDate> paymentTermsDueDate() {
        return (Optional<PaymentTermsDueDate>) paymentTermsDueDate;
    }

    /**
     * Indicates if late payment fees can be charged.
     */
    @JsonIgnore
    public JsonNullable<Boolean> canChargeLatePaymentFees() {
        return canChargeLatePaymentFees;
    }

    /**
     * Percentage fee charged on late payments.
     */
    @JsonIgnore
    public JsonNullable<Double> latePaymentFeePercent() {
        return latePaymentFeePercent;
    }

    /**
     * Currency code for the liability cap amount.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<CurrencyCode> liabilityCapCurrencyCode() {
        return (JsonNullable<CurrencyCode>) liabilityCapCurrencyCode;
    }

    /**
     * Duration for the liability cap
     */
    @JsonIgnore
    public JsonNullable<String> liabilityCapDuration() {
        return liabilityCapDuration;
    }

    /**
     * Maximum liability cap in the agreement
     */
    @JsonIgnore
    public JsonNullable<Double> liabilityCapFixedAmount() {
        return liabilityCapFixedAmount;
    }

    /**
     * Multiplier applied to calculate the liability cap
     */
    @JsonIgnore
    public JsonNullable<Double> liabilityCapMultiplier() {
        return liabilityCapMultiplier;
    }

    /**
     * Maximum allowed percentage increase in prices, limited between 0 and 100.
     */
    @JsonIgnore
    public JsonNullable<Float> priceCapPercentIncrease() {
        return priceCapPercentIncrease;
    }

    /**
     * The duration of the auto-renewal period.
     */
    @JsonIgnore
    public JsonNullable<String> autoRenewalTermLength() {
        return autoRenewalTermLength;
    }

    /**
     * Additional information related to the renewal process.
     */
    @JsonIgnore
    public JsonNullable<String> renewalAdditionalInfo() {
        return renewalAdditionalInfo;
    }

    /**
     * The period an agreement has been extended after it has been renewed.
     */
    @JsonIgnore
    public JsonNullable<String> renewalExtensionPeriod() {
        return renewalExtensionPeriod;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonIgnore
    public Optional<String> renewalNoticeDate() {
        return renewalNoticeDate;
    }

    /**
     * The period of time that a party is required to provide to indicate their intention to renew an
     * agreement.
     */
    @JsonIgnore
    public JsonNullable<String> renewalNoticePeriod() {
        return renewalNoticePeriod;
    }

    /**
     * User ID of the person responsible for managing the renewal process
     */
    @JsonIgnore
    public Optional<String> renewalProcessOwner() {
        return renewalProcessOwner;
    }

    /**
     * Specifies the type of renewal (e.g., automatic, manual).
     */
    @JsonIgnore
    public JsonNullable<String> renewalType() {
        return renewalType;
    }

    /**
     * The specific duration that a party has to give notice before terminating the agreement due to a
     * significant breach or violation of terms.
     * This period allows the other party to address the cause or prepare for termination.
     */
    @JsonIgnore
    public JsonNullable<String> terminationPeriodForCause() {
        return terminationPeriodForCause;
    }

    /**
     * Specifies the required notice period that a party must provide before terminating the agreement for
     * convenience, without cause, under the terms outlined in the contract.
     */
    @JsonIgnore
    public JsonNullable<String> terminationPeriodForConvenience() {
        return terminationPeriodForConvenience;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonIgnore
    public Optional<String> effectiveDate() {
        return effectiveDate;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonIgnore
    public Optional<String> executionDate() {
        return executionDate;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    @JsonIgnore
    public Optional<String> expirationDate() {
        return expirationDate;
    }

    /**
     * Overall duration of the agreement.
     */
    @JsonIgnore
    public JsonNullable<String> termLength() {
        return termLength;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Provisions related to changes in control of the assigning party
     */
    public Provisions withAssignmentChangeOfControl(String assignmentChangeOfControl) {
        Utils.checkNotNull(assignmentChangeOfControl, "assignmentChangeOfControl");
        this.assignmentChangeOfControl = JsonNullable.of(assignmentChangeOfControl);
        return this;
    }

    /**
     * Provisions related to changes in control of the assigning party
     */
    public Provisions withAssignmentChangeOfControl(JsonNullable<String> assignmentChangeOfControl) {
        Utils.checkNotNull(assignmentChangeOfControl, "assignmentChangeOfControl");
        this.assignmentChangeOfControl = assignmentChangeOfControl;
        return this;
    }

    /**
     * Provisions for the termination of assignment rights
     */
    public Provisions withAssignmentTerminationRights(String assignmentTerminationRights) {
        Utils.checkNotNull(assignmentTerminationRights, "assignmentTerminationRights");
        this.assignmentTerminationRights = JsonNullable.of(assignmentTerminationRights);
        return this;
    }

    /**
     * Provisions for the termination of assignment rights
     */
    public Provisions withAssignmentTerminationRights(JsonNullable<String> assignmentTerminationRights) {
        Utils.checkNotNull(assignmentTerminationRights, "assignmentTerminationRights");
        this.assignmentTerminationRights = assignmentTerminationRights;
        return this;
    }

    /**
     * The type of assignment rights in the agreement (e.g., transferability)
     */
    public Provisions withAssignmentType(String assignmentType) {
        Utils.checkNotNull(assignmentType, "assignmentType");
        this.assignmentType = JsonNullable.of(assignmentType);
        return this;
    }

    /**
     * The type of assignment rights in the agreement (e.g., transferability)
     */
    public Provisions withAssignmentType(JsonNullable<String> assignmentType) {
        Utils.checkNotNull(assignmentType, "assignmentType");
        this.assignmentType = assignmentType;
        return this;
    }

    /**
     * A subset of ISO 8601 duration. Fractional or negative values are not supported.
     */
    public Provisions withConfidentialityObligationPeriod(String confidentialityObligationPeriod) {
        Utils.checkNotNull(confidentialityObligationPeriod, "confidentialityObligationPeriod");
        this.confidentialityObligationPeriod = JsonNullable.of(confidentialityObligationPeriod);
        return this;
    }

    /**
     * A subset of ISO 8601 duration. Fractional or negative values are not supported.
     */
    public Provisions withConfidentialityObligationPeriod(JsonNullable<String> confidentialityObligationPeriod) {
        Utils.checkNotNull(confidentialityObligationPeriod, "confidentialityObligationPeriod");
        this.confidentialityObligationPeriod = confidentialityObligationPeriod;
        return this;
    }

    /**
     * The governing law clause identifies the substantive law that will govern the rights and obligations
     * of the parties to the agreement.
     */
    public Provisions withGoverningLaw(String governingLaw) {
        Utils.checkNotNull(governingLaw, "governingLaw");
        this.governingLaw = JsonNullable.of(governingLaw);
        return this;
    }

    /**
     * The governing law clause identifies the substantive law that will govern the rights and obligations
     * of the parties to the agreement.
     */
    public Provisions withGoverningLaw(JsonNullable<String> governingLaw) {
        Utils.checkNotNull(governingLaw, "governingLaw");
        this.governingLaw = governingLaw;
        return this;
    }

    /**
     * A jurisdiction clause expressly sets out which courts or tribunals have the power to hear a dispute
     * which arises under the agreement.
     */
    public Provisions withJurisdiction(String jurisdiction) {
        Utils.checkNotNull(jurisdiction, "jurisdiction");
        this.jurisdiction = JsonNullable.of(jurisdiction);
        return this;
    }

    /**
     * A jurisdiction clause expressly sets out which courts or tribunals have the power to hear a dispute
     * which arises under the agreement.
     */
    public Provisions withJurisdiction(JsonNullable<String> jurisdiction) {
        Utils.checkNotNull(jurisdiction, "jurisdiction");
        this.jurisdiction = jurisdiction;
        return this;
    }

    /**
     * Type of non-disclosure agreement (e.g., unilateral, bilateral).
     */
    public Provisions withNdaType(String ndaType) {
        Utils.checkNotNull(ndaType, "ndaType");
        this.ndaType = JsonNullable.of(ndaType);
        return this;
    }

    /**
     * Type of non-disclosure agreement (e.g., unilateral, bilateral).
     */
    public Provisions withNdaType(JsonNullable<String> ndaType) {
        Utils.checkNotNull(ndaType, "ndaType");
        this.ndaType = ndaType;
        return this;
    }

    /**
     * Total annual value of the agreement.
     */
    public Provisions withAnnualAgreementValue(double annualAgreementValue) {
        Utils.checkNotNull(annualAgreementValue, "annualAgreementValue");
        this.annualAgreementValue = JsonNullable.of(annualAgreementValue);
        return this;
    }

    /**
     * Total annual value of the agreement.
     */
    public Provisions withAnnualAgreementValue(JsonNullable<Double> annualAgreementValue) {
        Utils.checkNotNull(annualAgreementValue, "annualAgreementValue");
        this.annualAgreementValue = annualAgreementValue;
        return this;
    }

    /**
     * Currency code (e.g., USD, EUR) for the agreement's annual value.
     */
    public Provisions withAnnualAgreementValueCurrencyCode(CurrencyCode annualAgreementValueCurrencyCode) {
        Utils.checkNotNull(annualAgreementValueCurrencyCode, "annualAgreementValueCurrencyCode");
        this.annualAgreementValueCurrencyCode = JsonNullable.of(annualAgreementValueCurrencyCode);
        return this;
    }

    /**
     * Currency code (e.g., USD, EUR) for the agreement's annual value.
     */
    public Provisions withAnnualAgreementValueCurrencyCode(JsonNullable<? extends CurrencyCode> annualAgreementValueCurrencyCode) {
        Utils.checkNotNull(annualAgreementValueCurrencyCode, "annualAgreementValueCurrencyCode");
        this.annualAgreementValueCurrencyCode = annualAgreementValueCurrencyCode;
        return this;
    }

    /**
     * Total value of the agreement.
     */
    public Provisions withTotalAgreementValue(double totalAgreementValue) {
        Utils.checkNotNull(totalAgreementValue, "totalAgreementValue");
        this.totalAgreementValue = JsonNullable.of(totalAgreementValue);
        return this;
    }

    /**
     * Total value of the agreement.
     */
    public Provisions withTotalAgreementValue(JsonNullable<Double> totalAgreementValue) {
        Utils.checkNotNull(totalAgreementValue, "totalAgreementValue");
        this.totalAgreementValue = totalAgreementValue;
        return this;
    }

    /**
     * Currency code (e.g., USD, EUR) for the agreement's total value.
     */
    public Provisions withTotalAgreementValueCurrencyCode(CurrencyCode totalAgreementValueCurrencyCode) {
        Utils.checkNotNull(totalAgreementValueCurrencyCode, "totalAgreementValueCurrencyCode");
        this.totalAgreementValueCurrencyCode = JsonNullable.of(totalAgreementValueCurrencyCode);
        return this;
    }

    /**
     * Currency code (e.g., USD, EUR) for the agreement's total value.
     */
    public Provisions withTotalAgreementValueCurrencyCode(JsonNullable<? extends CurrencyCode> totalAgreementValueCurrencyCode) {
        Utils.checkNotNull(totalAgreementValueCurrencyCode, "totalAgreementValueCurrencyCode");
        this.totalAgreementValueCurrencyCode = totalAgreementValueCurrencyCode;
        return this;
    }

    /**
     * Terms specifying the payment due date, based on a defined number of days or other conditions.
     */
    public Provisions withPaymentTermsDueDate(PaymentTermsDueDate paymentTermsDueDate) {
        Utils.checkNotNull(paymentTermsDueDate, "paymentTermsDueDate");
        this.paymentTermsDueDate = Optional.ofNullable(paymentTermsDueDate);
        return this;
    }


    /**
     * Terms specifying the payment due date, based on a defined number of days or other conditions.
     */
    public Provisions withPaymentTermsDueDate(Optional<? extends PaymentTermsDueDate> paymentTermsDueDate) {
        Utils.checkNotNull(paymentTermsDueDate, "paymentTermsDueDate");
        this.paymentTermsDueDate = paymentTermsDueDate;
        return this;
    }

    /**
     * Indicates if late payment fees can be charged.
     */
    public Provisions withCanChargeLatePaymentFees(boolean canChargeLatePaymentFees) {
        Utils.checkNotNull(canChargeLatePaymentFees, "canChargeLatePaymentFees");
        this.canChargeLatePaymentFees = JsonNullable.of(canChargeLatePaymentFees);
        return this;
    }

    /**
     * Indicates if late payment fees can be charged.
     */
    public Provisions withCanChargeLatePaymentFees(JsonNullable<Boolean> canChargeLatePaymentFees) {
        Utils.checkNotNull(canChargeLatePaymentFees, "canChargeLatePaymentFees");
        this.canChargeLatePaymentFees = canChargeLatePaymentFees;
        return this;
    }

    /**
     * Percentage fee charged on late payments.
     */
    public Provisions withLatePaymentFeePercent(double latePaymentFeePercent) {
        Utils.checkNotNull(latePaymentFeePercent, "latePaymentFeePercent");
        this.latePaymentFeePercent = JsonNullable.of(latePaymentFeePercent);
        return this;
    }

    /**
     * Percentage fee charged on late payments.
     */
    public Provisions withLatePaymentFeePercent(JsonNullable<Double> latePaymentFeePercent) {
        Utils.checkNotNull(latePaymentFeePercent, "latePaymentFeePercent");
        this.latePaymentFeePercent = latePaymentFeePercent;
        return this;
    }

    /**
     * Currency code for the liability cap amount.
     */
    public Provisions withLiabilityCapCurrencyCode(CurrencyCode liabilityCapCurrencyCode) {
        Utils.checkNotNull(liabilityCapCurrencyCode, "liabilityCapCurrencyCode");
        this.liabilityCapCurrencyCode = JsonNullable.of(liabilityCapCurrencyCode);
        return this;
    }

    /**
     * Currency code for the liability cap amount.
     */
    public Provisions withLiabilityCapCurrencyCode(JsonNullable<? extends CurrencyCode> liabilityCapCurrencyCode) {
        Utils.checkNotNull(liabilityCapCurrencyCode, "liabilityCapCurrencyCode");
        this.liabilityCapCurrencyCode = liabilityCapCurrencyCode;
        return this;
    }

    /**
     * Duration for the liability cap
     */
    public Provisions withLiabilityCapDuration(String liabilityCapDuration) {
        Utils.checkNotNull(liabilityCapDuration, "liabilityCapDuration");
        this.liabilityCapDuration = JsonNullable.of(liabilityCapDuration);
        return this;
    }

    /**
     * Duration for the liability cap
     */
    public Provisions withLiabilityCapDuration(JsonNullable<String> liabilityCapDuration) {
        Utils.checkNotNull(liabilityCapDuration, "liabilityCapDuration");
        this.liabilityCapDuration = liabilityCapDuration;
        return this;
    }

    /**
     * Maximum liability cap in the agreement
     */
    public Provisions withLiabilityCapFixedAmount(double liabilityCapFixedAmount) {
        Utils.checkNotNull(liabilityCapFixedAmount, "liabilityCapFixedAmount");
        this.liabilityCapFixedAmount = JsonNullable.of(liabilityCapFixedAmount);
        return this;
    }

    /**
     * Maximum liability cap in the agreement
     */
    public Provisions withLiabilityCapFixedAmount(JsonNullable<Double> liabilityCapFixedAmount) {
        Utils.checkNotNull(liabilityCapFixedAmount, "liabilityCapFixedAmount");
        this.liabilityCapFixedAmount = liabilityCapFixedAmount;
        return this;
    }

    /**
     * Multiplier applied to calculate the liability cap
     */
    public Provisions withLiabilityCapMultiplier(double liabilityCapMultiplier) {
        Utils.checkNotNull(liabilityCapMultiplier, "liabilityCapMultiplier");
        this.liabilityCapMultiplier = JsonNullable.of(liabilityCapMultiplier);
        return this;
    }

    /**
     * Multiplier applied to calculate the liability cap
     */
    public Provisions withLiabilityCapMultiplier(JsonNullable<Double> liabilityCapMultiplier) {
        Utils.checkNotNull(liabilityCapMultiplier, "liabilityCapMultiplier");
        this.liabilityCapMultiplier = liabilityCapMultiplier;
        return this;
    }

    /**
     * Maximum allowed percentage increase in prices, limited between 0 and 100.
     */
    public Provisions withPriceCapPercentIncrease(float priceCapPercentIncrease) {
        Utils.checkNotNull(priceCapPercentIncrease, "priceCapPercentIncrease");
        this.priceCapPercentIncrease = JsonNullable.of(priceCapPercentIncrease);
        return this;
    }

    /**
     * Maximum allowed percentage increase in prices, limited between 0 and 100.
     */
    public Provisions withPriceCapPercentIncrease(JsonNullable<Float> priceCapPercentIncrease) {
        Utils.checkNotNull(priceCapPercentIncrease, "priceCapPercentIncrease");
        this.priceCapPercentIncrease = priceCapPercentIncrease;
        return this;
    }

    /**
     * The duration of the auto-renewal period.
     */
    public Provisions withAutoRenewalTermLength(String autoRenewalTermLength) {
        Utils.checkNotNull(autoRenewalTermLength, "autoRenewalTermLength");
        this.autoRenewalTermLength = JsonNullable.of(autoRenewalTermLength);
        return this;
    }

    /**
     * The duration of the auto-renewal period.
     */
    public Provisions withAutoRenewalTermLength(JsonNullable<String> autoRenewalTermLength) {
        Utils.checkNotNull(autoRenewalTermLength, "autoRenewalTermLength");
        this.autoRenewalTermLength = autoRenewalTermLength;
        return this;
    }

    /**
     * Additional information related to the renewal process.
     */
    public Provisions withRenewalAdditionalInfo(String renewalAdditionalInfo) {
        Utils.checkNotNull(renewalAdditionalInfo, "renewalAdditionalInfo");
        this.renewalAdditionalInfo = JsonNullable.of(renewalAdditionalInfo);
        return this;
    }

    /**
     * Additional information related to the renewal process.
     */
    public Provisions withRenewalAdditionalInfo(JsonNullable<String> renewalAdditionalInfo) {
        Utils.checkNotNull(renewalAdditionalInfo, "renewalAdditionalInfo");
        this.renewalAdditionalInfo = renewalAdditionalInfo;
        return this;
    }

    /**
     * The period an agreement has been extended after it has been renewed.
     */
    public Provisions withRenewalExtensionPeriod(String renewalExtensionPeriod) {
        Utils.checkNotNull(renewalExtensionPeriod, "renewalExtensionPeriod");
        this.renewalExtensionPeriod = JsonNullable.of(renewalExtensionPeriod);
        return this;
    }

    /**
     * The period an agreement has been extended after it has been renewed.
     */
    public Provisions withRenewalExtensionPeriod(JsonNullable<String> renewalExtensionPeriod) {
        Utils.checkNotNull(renewalExtensionPeriod, "renewalExtensionPeriod");
        this.renewalExtensionPeriod = renewalExtensionPeriod;
        return this;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withRenewalNoticeDate(String renewalNoticeDate) {
        Utils.checkNotNull(renewalNoticeDate, "renewalNoticeDate");
        this.renewalNoticeDate = Optional.ofNullable(renewalNoticeDate);
        return this;
    }


    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withRenewalNoticeDate(Optional<String> renewalNoticeDate) {
        Utils.checkNotNull(renewalNoticeDate, "renewalNoticeDate");
        this.renewalNoticeDate = renewalNoticeDate;
        return this;
    }

    /**
     * The period of time that a party is required to provide to indicate their intention to renew an
     * agreement.
     */
    public Provisions withRenewalNoticePeriod(String renewalNoticePeriod) {
        Utils.checkNotNull(renewalNoticePeriod, "renewalNoticePeriod");
        this.renewalNoticePeriod = JsonNullable.of(renewalNoticePeriod);
        return this;
    }

    /**
     * The period of time that a party is required to provide to indicate their intention to renew an
     * agreement.
     */
    public Provisions withRenewalNoticePeriod(JsonNullable<String> renewalNoticePeriod) {
        Utils.checkNotNull(renewalNoticePeriod, "renewalNoticePeriod");
        this.renewalNoticePeriod = renewalNoticePeriod;
        return this;
    }

    /**
     * User ID of the person responsible for managing the renewal process
     */
    public Provisions withRenewalProcessOwner(String renewalProcessOwner) {
        Utils.checkNotNull(renewalProcessOwner, "renewalProcessOwner");
        this.renewalProcessOwner = Optional.ofNullable(renewalProcessOwner);
        return this;
    }


    /**
     * User ID of the person responsible for managing the renewal process
     */
    public Provisions withRenewalProcessOwner(Optional<String> renewalProcessOwner) {
        Utils.checkNotNull(renewalProcessOwner, "renewalProcessOwner");
        this.renewalProcessOwner = renewalProcessOwner;
        return this;
    }

    /**
     * Specifies the type of renewal (e.g., automatic, manual).
     */
    public Provisions withRenewalType(String renewalType) {
        Utils.checkNotNull(renewalType, "renewalType");
        this.renewalType = JsonNullable.of(renewalType);
        return this;
    }

    /**
     * Specifies the type of renewal (e.g., automatic, manual).
     */
    public Provisions withRenewalType(JsonNullable<String> renewalType) {
        Utils.checkNotNull(renewalType, "renewalType");
        this.renewalType = renewalType;
        return this;
    }

    /**
     * The specific duration that a party has to give notice before terminating the agreement due to a
     * significant breach or violation of terms.
     * This period allows the other party to address the cause or prepare for termination.
     */
    public Provisions withTerminationPeriodForCause(String terminationPeriodForCause) {
        Utils.checkNotNull(terminationPeriodForCause, "terminationPeriodForCause");
        this.terminationPeriodForCause = JsonNullable.of(terminationPeriodForCause);
        return this;
    }

    /**
     * The specific duration that a party has to give notice before terminating the agreement due to a
     * significant breach or violation of terms.
     * This period allows the other party to address the cause or prepare for termination.
     */
    public Provisions withTerminationPeriodForCause(JsonNullable<String> terminationPeriodForCause) {
        Utils.checkNotNull(terminationPeriodForCause, "terminationPeriodForCause");
        this.terminationPeriodForCause = terminationPeriodForCause;
        return this;
    }

    /**
     * Specifies the required notice period that a party must provide before terminating the agreement for
     * convenience, without cause, under the terms outlined in the contract.
     */
    public Provisions withTerminationPeriodForConvenience(String terminationPeriodForConvenience) {
        Utils.checkNotNull(terminationPeriodForConvenience, "terminationPeriodForConvenience");
        this.terminationPeriodForConvenience = JsonNullable.of(terminationPeriodForConvenience);
        return this;
    }

    /**
     * Specifies the required notice period that a party must provide before terminating the agreement for
     * convenience, without cause, under the terms outlined in the contract.
     */
    public Provisions withTerminationPeriodForConvenience(JsonNullable<String> terminationPeriodForConvenience) {
        Utils.checkNotNull(terminationPeriodForConvenience, "terminationPeriodForConvenience");
        this.terminationPeriodForConvenience = terminationPeriodForConvenience;
        return this;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withEffectiveDate(String effectiveDate) {
        Utils.checkNotNull(effectiveDate, "effectiveDate");
        this.effectiveDate = Optional.ofNullable(effectiveDate);
        return this;
    }


    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withEffectiveDate(Optional<String> effectiveDate) {
        Utils.checkNotNull(effectiveDate, "effectiveDate");
        this.effectiveDate = effectiveDate;
        return this;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withExecutionDate(String executionDate) {
        Utils.checkNotNull(executionDate, "executionDate");
        this.executionDate = Optional.ofNullable(executionDate);
        return this;
    }


    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withExecutionDate(Optional<String> executionDate) {
        Utils.checkNotNull(executionDate, "executionDate");
        this.executionDate = executionDate;
        return this;
    }

    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withExpirationDate(String expirationDate) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        this.expirationDate = Optional.ofNullable(expirationDate);
        return this;
    }


    /**
     * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
     * explicit offset (e.g., +05:30, -0800).
     */
    public Provisions withExpirationDate(Optional<String> expirationDate) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * Overall duration of the agreement.
     */
    public Provisions withTermLength(String termLength) {
        Utils.checkNotNull(termLength, "termLength");
        this.termLength = JsonNullable.of(termLength);
        return this;
    }

    /**
     * Overall duration of the agreement.
     */
    public Provisions withTermLength(JsonNullable<String> termLength) {
        Utils.checkNotNull(termLength, "termLength");
        this.termLength = termLength;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Provisions other = (Provisions) o;
        return 
            Utils.enhancedDeepEquals(this.assignmentChangeOfControl, other.assignmentChangeOfControl) &&
            Utils.enhancedDeepEquals(this.assignmentTerminationRights, other.assignmentTerminationRights) &&
            Utils.enhancedDeepEquals(this.assignmentType, other.assignmentType) &&
            Utils.enhancedDeepEquals(this.confidentialityObligationPeriod, other.confidentialityObligationPeriod) &&
            Utils.enhancedDeepEquals(this.governingLaw, other.governingLaw) &&
            Utils.enhancedDeepEquals(this.jurisdiction, other.jurisdiction) &&
            Utils.enhancedDeepEquals(this.ndaType, other.ndaType) &&
            Utils.enhancedDeepEquals(this.annualAgreementValue, other.annualAgreementValue) &&
            Utils.enhancedDeepEquals(this.annualAgreementValueCurrencyCode, other.annualAgreementValueCurrencyCode) &&
            Utils.enhancedDeepEquals(this.totalAgreementValue, other.totalAgreementValue) &&
            Utils.enhancedDeepEquals(this.totalAgreementValueCurrencyCode, other.totalAgreementValueCurrencyCode) &&
            Utils.enhancedDeepEquals(this.paymentTermsDueDate, other.paymentTermsDueDate) &&
            Utils.enhancedDeepEquals(this.canChargeLatePaymentFees, other.canChargeLatePaymentFees) &&
            Utils.enhancedDeepEquals(this.latePaymentFeePercent, other.latePaymentFeePercent) &&
            Utils.enhancedDeepEquals(this.liabilityCapCurrencyCode, other.liabilityCapCurrencyCode) &&
            Utils.enhancedDeepEquals(this.liabilityCapDuration, other.liabilityCapDuration) &&
            Utils.enhancedDeepEquals(this.liabilityCapFixedAmount, other.liabilityCapFixedAmount) &&
            Utils.enhancedDeepEquals(this.liabilityCapMultiplier, other.liabilityCapMultiplier) &&
            Utils.enhancedDeepEquals(this.priceCapPercentIncrease, other.priceCapPercentIncrease) &&
            Utils.enhancedDeepEquals(this.autoRenewalTermLength, other.autoRenewalTermLength) &&
            Utils.enhancedDeepEquals(this.renewalAdditionalInfo, other.renewalAdditionalInfo) &&
            Utils.enhancedDeepEquals(this.renewalExtensionPeriod, other.renewalExtensionPeriod) &&
            Utils.enhancedDeepEquals(this.renewalNoticeDate, other.renewalNoticeDate) &&
            Utils.enhancedDeepEquals(this.renewalNoticePeriod, other.renewalNoticePeriod) &&
            Utils.enhancedDeepEquals(this.renewalProcessOwner, other.renewalProcessOwner) &&
            Utils.enhancedDeepEquals(this.renewalType, other.renewalType) &&
            Utils.enhancedDeepEquals(this.terminationPeriodForCause, other.terminationPeriodForCause) &&
            Utils.enhancedDeepEquals(this.terminationPeriodForConvenience, other.terminationPeriodForConvenience) &&
            Utils.enhancedDeepEquals(this.effectiveDate, other.effectiveDate) &&
            Utils.enhancedDeepEquals(this.executionDate, other.executionDate) &&
            Utils.enhancedDeepEquals(this.expirationDate, other.expirationDate) &&
            Utils.enhancedDeepEquals(this.termLength, other.termLength);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            assignmentChangeOfControl, assignmentTerminationRights, assignmentType,
            confidentialityObligationPeriod, governingLaw, jurisdiction,
            ndaType, annualAgreementValue, annualAgreementValueCurrencyCode,
            totalAgreementValue, totalAgreementValueCurrencyCode, paymentTermsDueDate,
            canChargeLatePaymentFees, latePaymentFeePercent, liabilityCapCurrencyCode,
            liabilityCapDuration, liabilityCapFixedAmount, liabilityCapMultiplier,
            priceCapPercentIncrease, autoRenewalTermLength, renewalAdditionalInfo,
            renewalExtensionPeriod, renewalNoticeDate, renewalNoticePeriod,
            renewalProcessOwner, renewalType, terminationPeriodForCause,
            terminationPeriodForConvenience, effectiveDate, executionDate,
            expirationDate, termLength);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Provisions.class,
                "assignmentChangeOfControl", assignmentChangeOfControl,
                "assignmentTerminationRights", assignmentTerminationRights,
                "assignmentType", assignmentType,
                "confidentialityObligationPeriod", confidentialityObligationPeriod,
                "governingLaw", governingLaw,
                "jurisdiction", jurisdiction,
                "ndaType", ndaType,
                "annualAgreementValue", annualAgreementValue,
                "annualAgreementValueCurrencyCode", annualAgreementValueCurrencyCode,
                "totalAgreementValue", totalAgreementValue,
                "totalAgreementValueCurrencyCode", totalAgreementValueCurrencyCode,
                "paymentTermsDueDate", paymentTermsDueDate,
                "canChargeLatePaymentFees", canChargeLatePaymentFees,
                "latePaymentFeePercent", latePaymentFeePercent,
                "liabilityCapCurrencyCode", liabilityCapCurrencyCode,
                "liabilityCapDuration", liabilityCapDuration,
                "liabilityCapFixedAmount", liabilityCapFixedAmount,
                "liabilityCapMultiplier", liabilityCapMultiplier,
                "priceCapPercentIncrease", priceCapPercentIncrease,
                "autoRenewalTermLength", autoRenewalTermLength,
                "renewalAdditionalInfo", renewalAdditionalInfo,
                "renewalExtensionPeriod", renewalExtensionPeriod,
                "renewalNoticeDate", renewalNoticeDate,
                "renewalNoticePeriod", renewalNoticePeriod,
                "renewalProcessOwner", renewalProcessOwner,
                "renewalType", renewalType,
                "terminationPeriodForCause", terminationPeriodForCause,
                "terminationPeriodForConvenience", terminationPeriodForConvenience,
                "effectiveDate", effectiveDate,
                "executionDate", executionDate,
                "expirationDate", expirationDate,
                "termLength", termLength);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> assignmentChangeOfControl = JsonNullable.undefined();

        private JsonNullable<String> assignmentTerminationRights = JsonNullable.undefined();

        private JsonNullable<String> assignmentType = JsonNullable.undefined();

        private JsonNullable<String> confidentialityObligationPeriod = JsonNullable.undefined();

        private JsonNullable<String> governingLaw = JsonNullable.undefined();

        private JsonNullable<String> jurisdiction = JsonNullable.undefined();

        private JsonNullable<String> ndaType = JsonNullable.undefined();

        private JsonNullable<Double> annualAgreementValue = JsonNullable.undefined();

        private JsonNullable<? extends CurrencyCode> annualAgreementValueCurrencyCode = JsonNullable.undefined();

        private JsonNullable<Double> totalAgreementValue = JsonNullable.undefined();

        private JsonNullable<? extends CurrencyCode> totalAgreementValueCurrencyCode = JsonNullable.undefined();

        private Optional<? extends PaymentTermsDueDate> paymentTermsDueDate;

        private JsonNullable<Boolean> canChargeLatePaymentFees = JsonNullable.undefined();

        private JsonNullable<Double> latePaymentFeePercent = JsonNullable.undefined();

        private JsonNullable<? extends CurrencyCode> liabilityCapCurrencyCode = JsonNullable.undefined();

        private JsonNullable<String> liabilityCapDuration = JsonNullable.undefined();

        private JsonNullable<Double> liabilityCapFixedAmount = JsonNullable.undefined();

        private JsonNullable<Double> liabilityCapMultiplier = JsonNullable.undefined();

        private JsonNullable<Float> priceCapPercentIncrease = JsonNullable.undefined();

        private JsonNullable<String> autoRenewalTermLength = JsonNullable.undefined();

        private JsonNullable<String> renewalAdditionalInfo = JsonNullable.undefined();

        private JsonNullable<String> renewalExtensionPeriod = JsonNullable.undefined();

        private Optional<String> renewalNoticeDate = Optional.empty();

        private JsonNullable<String> renewalNoticePeriod = JsonNullable.undefined();

        private Optional<String> renewalProcessOwner = Optional.empty();

        private JsonNullable<String> renewalType = JsonNullable.undefined();

        private JsonNullable<String> terminationPeriodForCause = JsonNullable.undefined();

        private JsonNullable<String> terminationPeriodForConvenience = JsonNullable.undefined();

        private Optional<String> effectiveDate = Optional.empty();

        private Optional<String> executionDate = Optional.empty();

        private Optional<String> expirationDate = Optional.empty();

        private JsonNullable<String> termLength = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Provisions related to changes in control of the assigning party
         */
        public Builder assignmentChangeOfControl(String assignmentChangeOfControl) {
            Utils.checkNotNull(assignmentChangeOfControl, "assignmentChangeOfControl");
            this.assignmentChangeOfControl = JsonNullable.of(assignmentChangeOfControl);
            return this;
        }

        /**
         * Provisions related to changes in control of the assigning party
         */
        public Builder assignmentChangeOfControl(JsonNullable<String> assignmentChangeOfControl) {
            Utils.checkNotNull(assignmentChangeOfControl, "assignmentChangeOfControl");
            this.assignmentChangeOfControl = assignmentChangeOfControl;
            return this;
        }


        /**
         * Provisions for the termination of assignment rights
         */
        public Builder assignmentTerminationRights(String assignmentTerminationRights) {
            Utils.checkNotNull(assignmentTerminationRights, "assignmentTerminationRights");
            this.assignmentTerminationRights = JsonNullable.of(assignmentTerminationRights);
            return this;
        }

        /**
         * Provisions for the termination of assignment rights
         */
        public Builder assignmentTerminationRights(JsonNullable<String> assignmentTerminationRights) {
            Utils.checkNotNull(assignmentTerminationRights, "assignmentTerminationRights");
            this.assignmentTerminationRights = assignmentTerminationRights;
            return this;
        }


        /**
         * The type of assignment rights in the agreement (e.g., transferability)
         */
        public Builder assignmentType(String assignmentType) {
            Utils.checkNotNull(assignmentType, "assignmentType");
            this.assignmentType = JsonNullable.of(assignmentType);
            return this;
        }

        /**
         * The type of assignment rights in the agreement (e.g., transferability)
         */
        public Builder assignmentType(JsonNullable<String> assignmentType) {
            Utils.checkNotNull(assignmentType, "assignmentType");
            this.assignmentType = assignmentType;
            return this;
        }


        /**
         * A subset of ISO 8601 duration. Fractional or negative values are not supported.
         */
        public Builder confidentialityObligationPeriod(String confidentialityObligationPeriod) {
            Utils.checkNotNull(confidentialityObligationPeriod, "confidentialityObligationPeriod");
            this.confidentialityObligationPeriod = JsonNullable.of(confidentialityObligationPeriod);
            return this;
        }

        /**
         * A subset of ISO 8601 duration. Fractional or negative values are not supported.
         */
        public Builder confidentialityObligationPeriod(JsonNullable<String> confidentialityObligationPeriod) {
            Utils.checkNotNull(confidentialityObligationPeriod, "confidentialityObligationPeriod");
            this.confidentialityObligationPeriod = confidentialityObligationPeriod;
            return this;
        }


        /**
         * The governing law clause identifies the substantive law that will govern the rights and obligations
         * of the parties to the agreement.
         */
        public Builder governingLaw(String governingLaw) {
            Utils.checkNotNull(governingLaw, "governingLaw");
            this.governingLaw = JsonNullable.of(governingLaw);
            return this;
        }

        /**
         * The governing law clause identifies the substantive law that will govern the rights and obligations
         * of the parties to the agreement.
         */
        public Builder governingLaw(JsonNullable<String> governingLaw) {
            Utils.checkNotNull(governingLaw, "governingLaw");
            this.governingLaw = governingLaw;
            return this;
        }


        /**
         * A jurisdiction clause expressly sets out which courts or tribunals have the power to hear a dispute
         * which arises under the agreement.
         */
        public Builder jurisdiction(String jurisdiction) {
            Utils.checkNotNull(jurisdiction, "jurisdiction");
            this.jurisdiction = JsonNullable.of(jurisdiction);
            return this;
        }

        /**
         * A jurisdiction clause expressly sets out which courts or tribunals have the power to hear a dispute
         * which arises under the agreement.
         */
        public Builder jurisdiction(JsonNullable<String> jurisdiction) {
            Utils.checkNotNull(jurisdiction, "jurisdiction");
            this.jurisdiction = jurisdiction;
            return this;
        }


        /**
         * Type of non-disclosure agreement (e.g., unilateral, bilateral).
         */
        public Builder ndaType(String ndaType) {
            Utils.checkNotNull(ndaType, "ndaType");
            this.ndaType = JsonNullable.of(ndaType);
            return this;
        }

        /**
         * Type of non-disclosure agreement (e.g., unilateral, bilateral).
         */
        public Builder ndaType(JsonNullable<String> ndaType) {
            Utils.checkNotNull(ndaType, "ndaType");
            this.ndaType = ndaType;
            return this;
        }


        /**
         * Total annual value of the agreement.
         */
        public Builder annualAgreementValue(double annualAgreementValue) {
            Utils.checkNotNull(annualAgreementValue, "annualAgreementValue");
            this.annualAgreementValue = JsonNullable.of(annualAgreementValue);
            return this;
        }

        /**
         * Total annual value of the agreement.
         */
        public Builder annualAgreementValue(JsonNullable<Double> annualAgreementValue) {
            Utils.checkNotNull(annualAgreementValue, "annualAgreementValue");
            this.annualAgreementValue = annualAgreementValue;
            return this;
        }


        /**
         * Currency code (e.g., USD, EUR) for the agreement's annual value.
         */
        public Builder annualAgreementValueCurrencyCode(CurrencyCode annualAgreementValueCurrencyCode) {
            Utils.checkNotNull(annualAgreementValueCurrencyCode, "annualAgreementValueCurrencyCode");
            this.annualAgreementValueCurrencyCode = JsonNullable.of(annualAgreementValueCurrencyCode);
            return this;
        }

        /**
         * Currency code (e.g., USD, EUR) for the agreement's annual value.
         */
        public Builder annualAgreementValueCurrencyCode(JsonNullable<? extends CurrencyCode> annualAgreementValueCurrencyCode) {
            Utils.checkNotNull(annualAgreementValueCurrencyCode, "annualAgreementValueCurrencyCode");
            this.annualAgreementValueCurrencyCode = annualAgreementValueCurrencyCode;
            return this;
        }


        /**
         * Total value of the agreement.
         */
        public Builder totalAgreementValue(double totalAgreementValue) {
            Utils.checkNotNull(totalAgreementValue, "totalAgreementValue");
            this.totalAgreementValue = JsonNullable.of(totalAgreementValue);
            return this;
        }

        /**
         * Total value of the agreement.
         */
        public Builder totalAgreementValue(JsonNullable<Double> totalAgreementValue) {
            Utils.checkNotNull(totalAgreementValue, "totalAgreementValue");
            this.totalAgreementValue = totalAgreementValue;
            return this;
        }


        /**
         * Currency code (e.g., USD, EUR) for the agreement's total value.
         */
        public Builder totalAgreementValueCurrencyCode(CurrencyCode totalAgreementValueCurrencyCode) {
            Utils.checkNotNull(totalAgreementValueCurrencyCode, "totalAgreementValueCurrencyCode");
            this.totalAgreementValueCurrencyCode = JsonNullable.of(totalAgreementValueCurrencyCode);
            return this;
        }

        /**
         * Currency code (e.g., USD, EUR) for the agreement's total value.
         */
        public Builder totalAgreementValueCurrencyCode(JsonNullable<? extends CurrencyCode> totalAgreementValueCurrencyCode) {
            Utils.checkNotNull(totalAgreementValueCurrencyCode, "totalAgreementValueCurrencyCode");
            this.totalAgreementValueCurrencyCode = totalAgreementValueCurrencyCode;
            return this;
        }


        /**
         * Terms specifying the payment due date, based on a defined number of days or other conditions.
         */
        public Builder paymentTermsDueDate(PaymentTermsDueDate paymentTermsDueDate) {
            Utils.checkNotNull(paymentTermsDueDate, "paymentTermsDueDate");
            this.paymentTermsDueDate = Optional.ofNullable(paymentTermsDueDate);
            return this;
        }

        /**
         * Terms specifying the payment due date, based on a defined number of days or other conditions.
         */
        public Builder paymentTermsDueDate(Optional<? extends PaymentTermsDueDate> paymentTermsDueDate) {
            Utils.checkNotNull(paymentTermsDueDate, "paymentTermsDueDate");
            this.paymentTermsDueDate = paymentTermsDueDate;
            return this;
        }


        /**
         * Indicates if late payment fees can be charged.
         */
        public Builder canChargeLatePaymentFees(boolean canChargeLatePaymentFees) {
            Utils.checkNotNull(canChargeLatePaymentFees, "canChargeLatePaymentFees");
            this.canChargeLatePaymentFees = JsonNullable.of(canChargeLatePaymentFees);
            return this;
        }

        /**
         * Indicates if late payment fees can be charged.
         */
        public Builder canChargeLatePaymentFees(JsonNullable<Boolean> canChargeLatePaymentFees) {
            Utils.checkNotNull(canChargeLatePaymentFees, "canChargeLatePaymentFees");
            this.canChargeLatePaymentFees = canChargeLatePaymentFees;
            return this;
        }


        /**
         * Percentage fee charged on late payments.
         */
        public Builder latePaymentFeePercent(double latePaymentFeePercent) {
            Utils.checkNotNull(latePaymentFeePercent, "latePaymentFeePercent");
            this.latePaymentFeePercent = JsonNullable.of(latePaymentFeePercent);
            return this;
        }

        /**
         * Percentage fee charged on late payments.
         */
        public Builder latePaymentFeePercent(JsonNullable<Double> latePaymentFeePercent) {
            Utils.checkNotNull(latePaymentFeePercent, "latePaymentFeePercent");
            this.latePaymentFeePercent = latePaymentFeePercent;
            return this;
        }


        /**
         * Currency code for the liability cap amount.
         */
        public Builder liabilityCapCurrencyCode(CurrencyCode liabilityCapCurrencyCode) {
            Utils.checkNotNull(liabilityCapCurrencyCode, "liabilityCapCurrencyCode");
            this.liabilityCapCurrencyCode = JsonNullable.of(liabilityCapCurrencyCode);
            return this;
        }

        /**
         * Currency code for the liability cap amount.
         */
        public Builder liabilityCapCurrencyCode(JsonNullable<? extends CurrencyCode> liabilityCapCurrencyCode) {
            Utils.checkNotNull(liabilityCapCurrencyCode, "liabilityCapCurrencyCode");
            this.liabilityCapCurrencyCode = liabilityCapCurrencyCode;
            return this;
        }


        /**
         * Duration for the liability cap
         */
        public Builder liabilityCapDuration(String liabilityCapDuration) {
            Utils.checkNotNull(liabilityCapDuration, "liabilityCapDuration");
            this.liabilityCapDuration = JsonNullable.of(liabilityCapDuration);
            return this;
        }

        /**
         * Duration for the liability cap
         */
        public Builder liabilityCapDuration(JsonNullable<String> liabilityCapDuration) {
            Utils.checkNotNull(liabilityCapDuration, "liabilityCapDuration");
            this.liabilityCapDuration = liabilityCapDuration;
            return this;
        }


        /**
         * Maximum liability cap in the agreement
         */
        public Builder liabilityCapFixedAmount(double liabilityCapFixedAmount) {
            Utils.checkNotNull(liabilityCapFixedAmount, "liabilityCapFixedAmount");
            this.liabilityCapFixedAmount = JsonNullable.of(liabilityCapFixedAmount);
            return this;
        }

        /**
         * Maximum liability cap in the agreement
         */
        public Builder liabilityCapFixedAmount(JsonNullable<Double> liabilityCapFixedAmount) {
            Utils.checkNotNull(liabilityCapFixedAmount, "liabilityCapFixedAmount");
            this.liabilityCapFixedAmount = liabilityCapFixedAmount;
            return this;
        }


        /**
         * Multiplier applied to calculate the liability cap
         */
        public Builder liabilityCapMultiplier(double liabilityCapMultiplier) {
            Utils.checkNotNull(liabilityCapMultiplier, "liabilityCapMultiplier");
            this.liabilityCapMultiplier = JsonNullable.of(liabilityCapMultiplier);
            return this;
        }

        /**
         * Multiplier applied to calculate the liability cap
         */
        public Builder liabilityCapMultiplier(JsonNullable<Double> liabilityCapMultiplier) {
            Utils.checkNotNull(liabilityCapMultiplier, "liabilityCapMultiplier");
            this.liabilityCapMultiplier = liabilityCapMultiplier;
            return this;
        }


        /**
         * Maximum allowed percentage increase in prices, limited between 0 and 100.
         */
        public Builder priceCapPercentIncrease(float priceCapPercentIncrease) {
            Utils.checkNotNull(priceCapPercentIncrease, "priceCapPercentIncrease");
            this.priceCapPercentIncrease = JsonNullable.of(priceCapPercentIncrease);
            return this;
        }

        /**
         * Maximum allowed percentage increase in prices, limited between 0 and 100.
         */
        public Builder priceCapPercentIncrease(JsonNullable<Float> priceCapPercentIncrease) {
            Utils.checkNotNull(priceCapPercentIncrease, "priceCapPercentIncrease");
            this.priceCapPercentIncrease = priceCapPercentIncrease;
            return this;
        }


        /**
         * The duration of the auto-renewal period.
         */
        public Builder autoRenewalTermLength(String autoRenewalTermLength) {
            Utils.checkNotNull(autoRenewalTermLength, "autoRenewalTermLength");
            this.autoRenewalTermLength = JsonNullable.of(autoRenewalTermLength);
            return this;
        }

        /**
         * The duration of the auto-renewal period.
         */
        public Builder autoRenewalTermLength(JsonNullable<String> autoRenewalTermLength) {
            Utils.checkNotNull(autoRenewalTermLength, "autoRenewalTermLength");
            this.autoRenewalTermLength = autoRenewalTermLength;
            return this;
        }


        /**
         * Additional information related to the renewal process.
         */
        public Builder renewalAdditionalInfo(String renewalAdditionalInfo) {
            Utils.checkNotNull(renewalAdditionalInfo, "renewalAdditionalInfo");
            this.renewalAdditionalInfo = JsonNullable.of(renewalAdditionalInfo);
            return this;
        }

        /**
         * Additional information related to the renewal process.
         */
        public Builder renewalAdditionalInfo(JsonNullable<String> renewalAdditionalInfo) {
            Utils.checkNotNull(renewalAdditionalInfo, "renewalAdditionalInfo");
            this.renewalAdditionalInfo = renewalAdditionalInfo;
            return this;
        }


        /**
         * The period an agreement has been extended after it has been renewed.
         */
        public Builder renewalExtensionPeriod(String renewalExtensionPeriod) {
            Utils.checkNotNull(renewalExtensionPeriod, "renewalExtensionPeriod");
            this.renewalExtensionPeriod = JsonNullable.of(renewalExtensionPeriod);
            return this;
        }

        /**
         * The period an agreement has been extended after it has been renewed.
         */
        public Builder renewalExtensionPeriod(JsonNullable<String> renewalExtensionPeriod) {
            Utils.checkNotNull(renewalExtensionPeriod, "renewalExtensionPeriod");
            this.renewalExtensionPeriod = renewalExtensionPeriod;
            return this;
        }


        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder renewalNoticeDate(String renewalNoticeDate) {
            Utils.checkNotNull(renewalNoticeDate, "renewalNoticeDate");
            this.renewalNoticeDate = Optional.ofNullable(renewalNoticeDate);
            return this;
        }

        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder renewalNoticeDate(Optional<String> renewalNoticeDate) {
            Utils.checkNotNull(renewalNoticeDate, "renewalNoticeDate");
            this.renewalNoticeDate = renewalNoticeDate;
            return this;
        }


        /**
         * The period of time that a party is required to provide to indicate their intention to renew an
         * agreement.
         */
        public Builder renewalNoticePeriod(String renewalNoticePeriod) {
            Utils.checkNotNull(renewalNoticePeriod, "renewalNoticePeriod");
            this.renewalNoticePeriod = JsonNullable.of(renewalNoticePeriod);
            return this;
        }

        /**
         * The period of time that a party is required to provide to indicate their intention to renew an
         * agreement.
         */
        public Builder renewalNoticePeriod(JsonNullable<String> renewalNoticePeriod) {
            Utils.checkNotNull(renewalNoticePeriod, "renewalNoticePeriod");
            this.renewalNoticePeriod = renewalNoticePeriod;
            return this;
        }


        /**
         * User ID of the person responsible for managing the renewal process
         */
        public Builder renewalProcessOwner(String renewalProcessOwner) {
            Utils.checkNotNull(renewalProcessOwner, "renewalProcessOwner");
            this.renewalProcessOwner = Optional.ofNullable(renewalProcessOwner);
            return this;
        }

        /**
         * User ID of the person responsible for managing the renewal process
         */
        public Builder renewalProcessOwner(Optional<String> renewalProcessOwner) {
            Utils.checkNotNull(renewalProcessOwner, "renewalProcessOwner");
            this.renewalProcessOwner = renewalProcessOwner;
            return this;
        }


        /**
         * Specifies the type of renewal (e.g., automatic, manual).
         */
        public Builder renewalType(String renewalType) {
            Utils.checkNotNull(renewalType, "renewalType");
            this.renewalType = JsonNullable.of(renewalType);
            return this;
        }

        /**
         * Specifies the type of renewal (e.g., automatic, manual).
         */
        public Builder renewalType(JsonNullable<String> renewalType) {
            Utils.checkNotNull(renewalType, "renewalType");
            this.renewalType = renewalType;
            return this;
        }


        /**
         * The specific duration that a party has to give notice before terminating the agreement due to a
         * significant breach or violation of terms.
         * This period allows the other party to address the cause or prepare for termination.
         */
        public Builder terminationPeriodForCause(String terminationPeriodForCause) {
            Utils.checkNotNull(terminationPeriodForCause, "terminationPeriodForCause");
            this.terminationPeriodForCause = JsonNullable.of(terminationPeriodForCause);
            return this;
        }

        /**
         * The specific duration that a party has to give notice before terminating the agreement due to a
         * significant breach or violation of terms.
         * This period allows the other party to address the cause or prepare for termination.
         */
        public Builder terminationPeriodForCause(JsonNullable<String> terminationPeriodForCause) {
            Utils.checkNotNull(terminationPeriodForCause, "terminationPeriodForCause");
            this.terminationPeriodForCause = terminationPeriodForCause;
            return this;
        }


        /**
         * Specifies the required notice period that a party must provide before terminating the agreement for
         * convenience, without cause, under the terms outlined in the contract.
         */
        public Builder terminationPeriodForConvenience(String terminationPeriodForConvenience) {
            Utils.checkNotNull(terminationPeriodForConvenience, "terminationPeriodForConvenience");
            this.terminationPeriodForConvenience = JsonNullable.of(terminationPeriodForConvenience);
            return this;
        }

        /**
         * Specifies the required notice period that a party must provide before terminating the agreement for
         * convenience, without cause, under the terms outlined in the contract.
         */
        public Builder terminationPeriodForConvenience(JsonNullable<String> terminationPeriodForConvenience) {
            Utils.checkNotNull(terminationPeriodForConvenience, "terminationPeriodForConvenience");
            this.terminationPeriodForConvenience = terminationPeriodForConvenience;
            return this;
        }


        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder effectiveDate(String effectiveDate) {
            Utils.checkNotNull(effectiveDate, "effectiveDate");
            this.effectiveDate = Optional.ofNullable(effectiveDate);
            return this;
        }

        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder effectiveDate(Optional<String> effectiveDate) {
            Utils.checkNotNull(effectiveDate, "effectiveDate");
            this.effectiveDate = effectiveDate;
            return this;
        }


        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder executionDate(String executionDate) {
            Utils.checkNotNull(executionDate, "executionDate");
            this.executionDate = Optional.ofNullable(executionDate);
            return this;
        }

        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder executionDate(Optional<String> executionDate) {
            Utils.checkNotNull(executionDate, "executionDate");
            this.executionDate = executionDate;
            return this;
        }


        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder expirationDate(String expirationDate) {
            Utils.checkNotNull(expirationDate, "expirationDate");
            this.expirationDate = Optional.ofNullable(expirationDate);
            return this;
        }

        /**
         * ISO 8601 formatted date-time string. May be local (no timezone), UTC (Z suffix), or include an
         * explicit offset (e.g., +05:30, -0800).
         */
        public Builder expirationDate(Optional<String> expirationDate) {
            Utils.checkNotNull(expirationDate, "expirationDate");
            this.expirationDate = expirationDate;
            return this;
        }


        /**
         * Overall duration of the agreement.
         */
        public Builder termLength(String termLength) {
            Utils.checkNotNull(termLength, "termLength");
            this.termLength = JsonNullable.of(termLength);
            return this;
        }

        /**
         * Overall duration of the agreement.
         */
        public Builder termLength(JsonNullable<String> termLength) {
            Utils.checkNotNull(termLength, "termLength");
            this.termLength = termLength;
            return this;
        }

        public Provisions build() {
            if (paymentTermsDueDate == null) {
                paymentTermsDueDate = _SINGLETON_VALUE_PaymentTermsDueDate.value();
            }

            return new Provisions(
                assignmentChangeOfControl, assignmentTerminationRights, assignmentType,
                confidentialityObligationPeriod, governingLaw, jurisdiction,
                ndaType, annualAgreementValue, annualAgreementValueCurrencyCode,
                totalAgreementValue, totalAgreementValueCurrencyCode, paymentTermsDueDate,
                canChargeLatePaymentFees, latePaymentFeePercent, liabilityCapCurrencyCode,
                liabilityCapDuration, liabilityCapFixedAmount, liabilityCapMultiplier,
                priceCapPercentIncrease, autoRenewalTermLength, renewalAdditionalInfo,
                renewalExtensionPeriod, renewalNoticeDate, renewalNoticePeriod,
                renewalProcessOwner, renewalType, terminationPeriodForCause,
                terminationPeriodForConvenience, effectiveDate, executionDate,
                expirationDate, termLength);
        }


        private static final LazySingletonValue<Optional<? extends PaymentTermsDueDate>> _SINGLETON_VALUE_PaymentTermsDueDate =
                new LazySingletonValue<>(
                        "payment_terms_due_date",
                        "\"OTHER\"",
                        new TypeReference<Optional<? extends PaymentTermsDueDate>>() {});
    }
}
