/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.LazySingletonValue;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * ResponseMetadata
 * 
 * <p>Control information and metadata for the response.
 */
public class ResponseMetadata {
    /**
     * The maximum number of items that can be returned in a single page.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("page_limit")
    private JsonNullable<Integer> pageLimit;

    /**
     * Unique identifier for the request, useful for tracking and debugging.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("request_id")
    private Optional<String> requestId;

    /**
     * The duration of time, in milliseconds, that the server took to process and respond
     * to the request. This is measured from the time the server received the request
     * until the time the response was sent.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("response_duration_ms")
    private Optional<Integer> responseDurationMs;

    /**
     * The timestamp indicating when the response was generated.
     */
    @JsonInclude(Include.ALWAYS)
    @JsonProperty("response_timestamp")
    private Optional<OffsetDateTime> responseTimestamp;

    @JsonCreator
    public ResponseMetadata(
            @JsonProperty("page_limit") JsonNullable<Integer> pageLimit,
            @JsonProperty("request_id") Optional<String> requestId,
            @JsonProperty("response_duration_ms") Optional<Integer> responseDurationMs,
            @JsonProperty("response_timestamp") Optional<OffsetDateTime> responseTimestamp) {
        Utils.checkNotNull(pageLimit, "pageLimit");
        Utils.checkNotNull(requestId, "requestId");
        Utils.checkNotNull(responseDurationMs, "responseDurationMs");
        Utils.checkNotNull(responseTimestamp, "responseTimestamp");
        this.pageLimit = pageLimit;
        this.requestId = requestId;
        this.responseDurationMs = responseDurationMs;
        this.responseTimestamp = responseTimestamp;
    }
    
    public ResponseMetadata() {
        this(JsonNullable.undefined(), Optional.empty(), Optional.empty(),
            Optional.empty());
    }

    /**
     * The maximum number of items that can be returned in a single page.
     */
    @JsonIgnore
    public JsonNullable<Integer> pageLimit() {
        return pageLimit;
    }

    /**
     * Unique identifier for the request, useful for tracking and debugging.
     */
    @JsonIgnore
    public Optional<String> requestId() {
        return requestId;
    }

    /**
     * The duration of time, in milliseconds, that the server took to process and respond
     * to the request. This is measured from the time the server received the request
     * until the time the response was sent.
     */
    @JsonIgnore
    public Optional<Integer> responseDurationMs() {
        return responseDurationMs;
    }

    /**
     * The timestamp indicating when the response was generated.
     */
    @JsonIgnore
    public Optional<OffsetDateTime> responseTimestamp() {
        return responseTimestamp;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The maximum number of items that can be returned in a single page.
     */
    public ResponseMetadata withPageLimit(int pageLimit) {
        Utils.checkNotNull(pageLimit, "pageLimit");
        this.pageLimit = JsonNullable.of(pageLimit);
        return this;
    }

    /**
     * The maximum number of items that can be returned in a single page.
     */
    public ResponseMetadata withPageLimit(JsonNullable<Integer> pageLimit) {
        Utils.checkNotNull(pageLimit, "pageLimit");
        this.pageLimit = pageLimit;
        return this;
    }

    /**
     * Unique identifier for the request, useful for tracking and debugging.
     */
    public ResponseMetadata withRequestId(String requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = Optional.ofNullable(requestId);
        return this;
    }


    /**
     * Unique identifier for the request, useful for tracking and debugging.
     */
    public ResponseMetadata withRequestId(Optional<String> requestId) {
        Utils.checkNotNull(requestId, "requestId");
        this.requestId = requestId;
        return this;
    }

    /**
     * The duration of time, in milliseconds, that the server took to process and respond
     * to the request. This is measured from the time the server received the request
     * until the time the response was sent.
     */
    public ResponseMetadata withResponseDurationMs(int responseDurationMs) {
        Utils.checkNotNull(responseDurationMs, "responseDurationMs");
        this.responseDurationMs = Optional.ofNullable(responseDurationMs);
        return this;
    }


    /**
     * The duration of time, in milliseconds, that the server took to process and respond
     * to the request. This is measured from the time the server received the request
     * until the time the response was sent.
     */
    public ResponseMetadata withResponseDurationMs(Optional<Integer> responseDurationMs) {
        Utils.checkNotNull(responseDurationMs, "responseDurationMs");
        this.responseDurationMs = responseDurationMs;
        return this;
    }

    /**
     * The timestamp indicating when the response was generated.
     */
    public ResponseMetadata withResponseTimestamp(OffsetDateTime responseTimestamp) {
        Utils.checkNotNull(responseTimestamp, "responseTimestamp");
        this.responseTimestamp = Optional.ofNullable(responseTimestamp);
        return this;
    }


    /**
     * The timestamp indicating when the response was generated.
     */
    public ResponseMetadata withResponseTimestamp(Optional<OffsetDateTime> responseTimestamp) {
        Utils.checkNotNull(responseTimestamp, "responseTimestamp");
        this.responseTimestamp = responseTimestamp;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ResponseMetadata other = (ResponseMetadata) o;
        return 
            Utils.enhancedDeepEquals(this.pageLimit, other.pageLimit) &&
            Utils.enhancedDeepEquals(this.requestId, other.requestId) &&
            Utils.enhancedDeepEquals(this.responseDurationMs, other.responseDurationMs) &&
            Utils.enhancedDeepEquals(this.responseTimestamp, other.responseTimestamp);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            pageLimit, requestId, responseDurationMs,
            responseTimestamp);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ResponseMetadata.class,
                "pageLimit", pageLimit,
                "requestId", requestId,
                "responseDurationMs", responseDurationMs,
                "responseTimestamp", responseTimestamp);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<Integer> pageLimit;

        private Optional<String> requestId = Optional.empty();

        private Optional<Integer> responseDurationMs = Optional.empty();

        private Optional<OffsetDateTime> responseTimestamp = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The maximum number of items that can be returned in a single page.
         */
        public Builder pageLimit(int pageLimit) {
            Utils.checkNotNull(pageLimit, "pageLimit");
            this.pageLimit = JsonNullable.of(pageLimit);
            return this;
        }

        /**
         * The maximum number of items that can be returned in a single page.
         */
        public Builder pageLimit(JsonNullable<Integer> pageLimit) {
            Utils.checkNotNull(pageLimit, "pageLimit");
            this.pageLimit = pageLimit;
            return this;
        }


        /**
         * Unique identifier for the request, useful for tracking and debugging.
         */
        public Builder requestId(String requestId) {
            Utils.checkNotNull(requestId, "requestId");
            this.requestId = Optional.ofNullable(requestId);
            return this;
        }

        /**
         * Unique identifier for the request, useful for tracking and debugging.
         */
        public Builder requestId(Optional<String> requestId) {
            Utils.checkNotNull(requestId, "requestId");
            this.requestId = requestId;
            return this;
        }


        /**
         * The duration of time, in milliseconds, that the server took to process and respond
         * to the request. This is measured from the time the server received the request
         * until the time the response was sent.
         */
        public Builder responseDurationMs(int responseDurationMs) {
            Utils.checkNotNull(responseDurationMs, "responseDurationMs");
            this.responseDurationMs = Optional.ofNullable(responseDurationMs);
            return this;
        }

        /**
         * The duration of time, in milliseconds, that the server took to process and respond
         * to the request. This is measured from the time the server received the request
         * until the time the response was sent.
         */
        public Builder responseDurationMs(Optional<Integer> responseDurationMs) {
            Utils.checkNotNull(responseDurationMs, "responseDurationMs");
            this.responseDurationMs = responseDurationMs;
            return this;
        }


        /**
         * The timestamp indicating when the response was generated.
         */
        public Builder responseTimestamp(OffsetDateTime responseTimestamp) {
            Utils.checkNotNull(responseTimestamp, "responseTimestamp");
            this.responseTimestamp = Optional.ofNullable(responseTimestamp);
            return this;
        }

        /**
         * The timestamp indicating when the response was generated.
         */
        public Builder responseTimestamp(Optional<OffsetDateTime> responseTimestamp) {
            Utils.checkNotNull(responseTimestamp, "responseTimestamp");
            this.responseTimestamp = responseTimestamp;
            return this;
        }

        public ResponseMetadata build() {
            if (pageLimit == null) {
                pageLimit = _SINGLETON_VALUE_PageLimit.value();
            }

            return new ResponseMetadata(
                pageLimit, requestId, responseDurationMs,
                responseTimestamp);
        }


        private static final LazySingletonValue<JsonNullable<Integer>> _SINGLETON_VALUE_PageLimit =
                new LazySingletonValue<>(
                        "page_limit",
                        "25",
                        new TypeReference<JsonNullable<Integer>>() {});
    }
}
