/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * SupportedOperation
 * 
 * <p>The operation that the field supports.
 */
public enum SupportedOperation {
    VERIFY_TYPE("VerifyType");

    @JsonValue
    private final String value;

    private SupportedOperation(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<SupportedOperation> fromValue(String value) {
        for (SupportedOperation o: SupportedOperation.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

