/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * TriggerEventType
 * 
 * <p>The type of event that triggers the workflow. In this case, the workflow is initiated
 * by an HTTP request. Future iterations may support additional event types beyond HTTP.
 */
public enum TriggerEventType {
    HTTP("HTTP");

    @JsonValue
    private final String value;

    TriggerEventType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<TriggerEventType> fromValue(String value) {
        for (TriggerEventType o: TriggerEventType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

