/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.components;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Optional;

public class WorkflowInstanceCollection {

    /**
     * Array of workflow instances
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Optional<? extends List<WorkflowInstance>> data;

    /**
     * Control information and metadata for the response.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("response_metadata")
    private Optional<? extends ResponseMetadata> responseMetadata;

    @JsonCreator
    public WorkflowInstanceCollection(
            @JsonProperty("data") Optional<? extends List<WorkflowInstance>> data,
            @JsonProperty("response_metadata") Optional<? extends ResponseMetadata> responseMetadata) {
        Utils.checkNotNull(data, "data");
        Utils.checkNotNull(responseMetadata, "responseMetadata");
        this.data = data;
        this.responseMetadata = responseMetadata;
    }
    
    public WorkflowInstanceCollection() {
        this(Optional.empty(), Optional.empty());
    }

    /**
     * Array of workflow instances
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<WorkflowInstance>> data() {
        return (Optional<List<WorkflowInstance>>) data;
    }

    /**
     * Control information and metadata for the response.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<ResponseMetadata> responseMetadata() {
        return (Optional<ResponseMetadata>) responseMetadata;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * Array of workflow instances
     */
    public WorkflowInstanceCollection withData(List<WorkflowInstance> data) {
        Utils.checkNotNull(data, "data");
        this.data = Optional.ofNullable(data);
        return this;
    }

    /**
     * Array of workflow instances
     */
    public WorkflowInstanceCollection withData(Optional<? extends List<WorkflowInstance>> data) {
        Utils.checkNotNull(data, "data");
        this.data = data;
        return this;
    }

    /**
     * Control information and metadata for the response.
     */
    public WorkflowInstanceCollection withResponseMetadata(ResponseMetadata responseMetadata) {
        Utils.checkNotNull(responseMetadata, "responseMetadata");
        this.responseMetadata = Optional.ofNullable(responseMetadata);
        return this;
    }

    /**
     * Control information and metadata for the response.
     */
    public WorkflowInstanceCollection withResponseMetadata(Optional<? extends ResponseMetadata> responseMetadata) {
        Utils.checkNotNull(responseMetadata, "responseMetadata");
        this.responseMetadata = responseMetadata;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        WorkflowInstanceCollection other = (WorkflowInstanceCollection) o;
        return 
            Utils.enhancedDeepEquals(this.data, other.data) &&
            Utils.enhancedDeepEquals(this.responseMetadata, other.responseMetadata);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            data,
            responseMetadata);
    }
    
    @Override
    public String toString() {
        return Utils.toString(WorkflowInstanceCollection.class,
                "data", data,
                "responseMetadata", responseMetadata);
    }
    
    public final static class Builder {
 
        private Optional<? extends List<WorkflowInstance>> data = Optional.empty();
 
        private Optional<? extends ResponseMetadata> responseMetadata = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Array of workflow instances
         */
        public Builder data(List<WorkflowInstance> data) {
            Utils.checkNotNull(data, "data");
            this.data = Optional.ofNullable(data);
            return this;
        }

        /**
         * Array of workflow instances
         */
        public Builder data(Optional<? extends List<WorkflowInstance>> data) {
            Utils.checkNotNull(data, "data");
            this.data = data;
            return this;
        }

        /**
         * Control information and metadata for the response.
         */
        public Builder responseMetadata(ResponseMetadata responseMetadata) {
            Utils.checkNotNull(responseMetadata, "responseMetadata");
            this.responseMetadata = Optional.ofNullable(responseMetadata);
            return this;
        }

        /**
         * Control information and metadata for the response.
         */
        public Builder responseMetadata(Optional<? extends ResponseMetadata> responseMetadata) {
            Utils.checkNotNull(responseMetadata, "responseMetadata");
            this.responseMetadata = responseMetadata;
            return this;
        }
        
        public WorkflowInstanceCollection build() {
            return new WorkflowInstanceCollection(
                data,
                responseMetadata);
        }
    }
}
