/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import static com.docusign.iam.sdk.operations.Operations.RequestOperation;

import com.docusign.iam.sdk.SDKConfiguration;
import com.docusign.iam.sdk.models.components.WorkspaceUserForCreate;
import com.docusign.iam.sdk.operations.AddWorkspaceUser;
import com.docusign.iam.sdk.utils.Options;
import com.docusign.iam.sdk.utils.RetryConfig;
import com.docusign.iam.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import java.util.Optional;

public class AddWorkspaceUserRequestBuilder {

    private String accountId;
    private String workspaceId;
    private Optional<? extends WorkspaceUserForCreate> workspaceUserForCreate = Optional.empty();
    private Optional<RetryConfig> retryConfig = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public AddWorkspaceUserRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public AddWorkspaceUserRequestBuilder accountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    public AddWorkspaceUserRequestBuilder workspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }
                
    public AddWorkspaceUserRequestBuilder workspaceUserForCreate(WorkspaceUserForCreate workspaceUserForCreate) {
        Utils.checkNotNull(workspaceUserForCreate, "workspaceUserForCreate");
        this.workspaceUserForCreate = Optional.of(workspaceUserForCreate);
        return this;
    }

    public AddWorkspaceUserRequestBuilder workspaceUserForCreate(Optional<? extends WorkspaceUserForCreate> workspaceUserForCreate) {
        Utils.checkNotNull(workspaceUserForCreate, "workspaceUserForCreate");
        this.workspaceUserForCreate = workspaceUserForCreate;
        return this;
    }
                
    public AddWorkspaceUserRequestBuilder retryConfig(RetryConfig retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = Optional.of(retryConfig);
        return this;
    }

    public AddWorkspaceUserRequestBuilder retryConfig(Optional<RetryConfig> retryConfig) {
        Utils.checkNotNull(retryConfig, "retryConfig");
        this.retryConfig = retryConfig;
        return this;
    }


    private AddWorkspaceUserRequest buildRequest() {

        AddWorkspaceUserRequest request = new AddWorkspaceUserRequest(accountId,
            workspaceId,
            workspaceUserForCreate);

        return request;
    }

    public AddWorkspaceUserResponse call() throws Exception {
        Optional<Options> options = Optional.of(Options.builder()
            .retryConfig(retryConfig)
            .build());

        RequestOperation<AddWorkspaceUserRequest, AddWorkspaceUserResponse> operation
              = new AddWorkspaceUser.Sync(sdkConfiguration, options);
        AddWorkspaceUserRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
