/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.models.components.TabInfo;
import com.docusign.iam.sdk.utils.Response;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.List;
import java.util.Optional;

public class ConnectedFieldsApiGetTabGroupsResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Successful response
     */
    private Optional<? extends List<TabInfo>> tabInfos;

    @JsonCreator
    public ConnectedFieldsApiGetTabGroupsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends List<TabInfo>> tabInfos) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(tabInfos, "tabInfos");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.tabInfos = tabInfos;
    }
    
    public ConnectedFieldsApiGetTabGroupsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Successful response
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<List<TabInfo>> tabInfos() {
        return (Optional<List<TabInfo>>) tabInfos;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public ConnectedFieldsApiGetTabGroupsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public ConnectedFieldsApiGetTabGroupsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public ConnectedFieldsApiGetTabGroupsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Successful response
     */
    public ConnectedFieldsApiGetTabGroupsResponse withTabInfos(List<TabInfo> tabInfos) {
        Utils.checkNotNull(tabInfos, "tabInfos");
        this.tabInfos = Optional.ofNullable(tabInfos);
        return this;
    }

    /**
     * Successful response
     */
    public ConnectedFieldsApiGetTabGroupsResponse withTabInfos(Optional<? extends List<TabInfo>> tabInfos) {
        Utils.checkNotNull(tabInfos, "tabInfos");
        this.tabInfos = tabInfos;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ConnectedFieldsApiGetTabGroupsResponse other = (ConnectedFieldsApiGetTabGroupsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.tabInfos, other.tabInfos);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType,
            statusCode,
            rawResponse,
            tabInfos);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ConnectedFieldsApiGetTabGroupsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "tabInfos", tabInfos);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends List<TabInfo>> tabInfos = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Successful response
         */
        public Builder tabInfos(List<TabInfo> tabInfos) {
            Utils.checkNotNull(tabInfos, "tabInfos");
            this.tabInfos = Optional.ofNullable(tabInfos);
            return this;
        }

        /**
         * Successful response
         */
        public Builder tabInfos(Optional<? extends List<TabInfo>> tabInfos) {
            Utils.checkNotNull(tabInfos, "tabInfos");
            this.tabInfos = tabInfos;
            return this;
        }
        
        public ConnectedFieldsApiGetTabGroupsResponse build() {
            return new ConnectedFieldsApiGetTabGroupsResponse(
                contentType,
                statusCode,
                rawResponse,
                tabInfos);
        }
    }
}
