/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.models.components.CreateBulkJob;
import com.docusign.iam.sdk.utils.LazySingletonValue;
import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;


public class CreateBulkUploadJobRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private CreateBulkJob createBulkJob;

    @JsonCreator
    public CreateBulkUploadJobRequest(
            String accountId,
            CreateBulkJob createBulkJob) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(createBulkJob, "createBulkJob");
        this.accountId = accountId;
        this.createBulkJob = createBulkJob;
    }

    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    @JsonIgnore
    public CreateBulkJob createBulkJob() {
        return createBulkJob;
    }

    public static Builder builder() {
        return new Builder();
    }


    public CreateBulkUploadJobRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    public CreateBulkUploadJobRequest withCreateBulkJob(CreateBulkJob createBulkJob) {
        Utils.checkNotNull(createBulkJob, "createBulkJob");
        this.createBulkJob = createBulkJob;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateBulkUploadJobRequest other = (CreateBulkUploadJobRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.createBulkJob, other.createBulkJob);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId, createBulkJob);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateBulkUploadJobRequest.class,
                "accountId", accountId,
                "createBulkJob", createBulkJob);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountId;

        private CreateBulkJob createBulkJob;

        private Builder() {
          // force use of static builder() method
        }


        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        public Builder createBulkJob(CreateBulkJob createBulkJob) {
            Utils.checkNotNull(createBulkJob, "createBulkJob");
            this.createBulkJob = createBulkJob;
            return this;
        }

        public CreateBulkUploadJobRequest build() {
            if (accountId == null) {
                accountId = _SINGLETON_VALUE_AccountId.value();
            }

            return new CreateBulkUploadJobRequest(
                accountId, createBulkJob);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_AccountId =
                new LazySingletonValue<>(
                        "accountId",
                        "\"00000000-0000-0000-0000-000000000000\"",
                        new TypeReference<String>() {});
    }
}
