/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;

public class DeleteAgreementRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=agreementId")
    private String agreementId;

    @JsonCreator
    public DeleteAgreementRequest(
            String accountId,
            String agreementId) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(agreementId, "agreementId");
        this.accountId = accountId;
        this.agreementId = agreementId;
    }

    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    @JsonIgnore
    public String agreementId() {
        return agreementId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public DeleteAgreementRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    public DeleteAgreementRequest withAgreementId(String agreementId) {
        Utils.checkNotNull(agreementId, "agreementId");
        this.agreementId = agreementId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        DeleteAgreementRequest other = (DeleteAgreementRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.agreementId, other.agreementId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId,
            agreementId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(DeleteAgreementRequest.class,
                "accountId", accountId,
                "agreementId", agreementId);
    }
    
    public final static class Builder {
 
        private String accountId;
 
        private String agreementId;
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }

        public Builder agreementId(String agreementId) {
            Utils.checkNotNull(agreementId, "agreementId");
            this.agreementId = agreementId;
            return this;
        }
        
        public DeleteAgreementRequest build() {
            return new DeleteAgreementRequest(
                accountId,
                agreementId);
        }
    }
}
