/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

/**
 * GetTokenFromJWTGrantGrantType
 * 
 * <p>The grant type.
 */
public enum GetTokenFromJWTGrantGrantType {
    URN_IETF_PARAMS_OAUTH_GRANT_TYPE_JWT_BEARER("urn:ietf:params:oauth:grant-type:jwt-bearer");

    @JsonValue
    private final String value;

    private GetTokenFromJWTGrantGrantType(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<GetTokenFromJWTGrantGrantType> fromValue(String value) {
        for (GetTokenFromJWTGrantGrantType o: GetTokenFromJWTGrantGrantType.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}

