/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;


public class GetWorkspaceDocumentsRequest {
    /**
     * The ID of the account
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;

    /**
     * The ID of the workspace
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceId")
    private String workspaceId;

    /**
     * Number of documents to return. Defaults to the maximum which is 100
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=count")
    private Optional<Integer> count;

    /**
     * Position of the first item in the total results. Defaults to 0
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=start_position")
    private Optional<Integer> startPosition;

    /**
     * Filter documents where Name contains the filter. Defaults to null, to not filter
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=name_filter")
    private Optional<String> nameFilter;

    @JsonCreator
    public GetWorkspaceDocumentsRequest(
            String accountId,
            String workspaceId,
            Optional<Integer> count,
            Optional<Integer> startPosition,
            Optional<String> nameFilter) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(workspaceId, "workspaceId");
        Utils.checkNotNull(count, "count");
        Utils.checkNotNull(startPosition, "startPosition");
        Utils.checkNotNull(nameFilter, "nameFilter");
        this.accountId = accountId;
        this.workspaceId = workspaceId;
        this.count = count;
        this.startPosition = startPosition;
        this.nameFilter = nameFilter;
    }
    
    public GetWorkspaceDocumentsRequest(
            String accountId,
            String workspaceId) {
        this(accountId, workspaceId, Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * The ID of the account
     */
    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    /**
     * The ID of the workspace
     */
    @JsonIgnore
    public String workspaceId() {
        return workspaceId;
    }

    /**
     * Number of documents to return. Defaults to the maximum which is 100
     */
    @JsonIgnore
    public Optional<Integer> count() {
        return count;
    }

    /**
     * Position of the first item in the total results. Defaults to 0
     */
    @JsonIgnore
    public Optional<Integer> startPosition() {
        return startPosition;
    }

    /**
     * Filter documents where Name contains the filter. Defaults to null, to not filter
     */
    @JsonIgnore
    public Optional<String> nameFilter() {
        return nameFilter;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the account
     */
    public GetWorkspaceDocumentsRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    /**
     * The ID of the workspace
     */
    public GetWorkspaceDocumentsRequest withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }

    /**
     * Number of documents to return. Defaults to the maximum which is 100
     */
    public GetWorkspaceDocumentsRequest withCount(int count) {
        Utils.checkNotNull(count, "count");
        this.count = Optional.ofNullable(count);
        return this;
    }


    /**
     * Number of documents to return. Defaults to the maximum which is 100
     */
    public GetWorkspaceDocumentsRequest withCount(Optional<Integer> count) {
        Utils.checkNotNull(count, "count");
        this.count = count;
        return this;
    }

    /**
     * Position of the first item in the total results. Defaults to 0
     */
    public GetWorkspaceDocumentsRequest withStartPosition(int startPosition) {
        Utils.checkNotNull(startPosition, "startPosition");
        this.startPosition = Optional.ofNullable(startPosition);
        return this;
    }


    /**
     * Position of the first item in the total results. Defaults to 0
     */
    public GetWorkspaceDocumentsRequest withStartPosition(Optional<Integer> startPosition) {
        Utils.checkNotNull(startPosition, "startPosition");
        this.startPosition = startPosition;
        return this;
    }

    /**
     * Filter documents where Name contains the filter. Defaults to null, to not filter
     */
    public GetWorkspaceDocumentsRequest withNameFilter(String nameFilter) {
        Utils.checkNotNull(nameFilter, "nameFilter");
        this.nameFilter = Optional.ofNullable(nameFilter);
        return this;
    }


    /**
     * Filter documents where Name contains the filter. Defaults to null, to not filter
     */
    public GetWorkspaceDocumentsRequest withNameFilter(Optional<String> nameFilter) {
        Utils.checkNotNull(nameFilter, "nameFilter");
        this.nameFilter = nameFilter;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceDocumentsRequest other = (GetWorkspaceDocumentsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.workspaceId, other.workspaceId) &&
            Utils.enhancedDeepEquals(this.count, other.count) &&
            Utils.enhancedDeepEquals(this.startPosition, other.startPosition) &&
            Utils.enhancedDeepEquals(this.nameFilter, other.nameFilter);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId, workspaceId, count,
            startPosition, nameFilter);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceDocumentsRequest.class,
                "accountId", accountId,
                "workspaceId", workspaceId,
                "count", count,
                "startPosition", startPosition,
                "nameFilter", nameFilter);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountId;

        private String workspaceId;

        private Optional<Integer> count = Optional.empty();

        private Optional<Integer> startPosition = Optional.empty();

        private Optional<String> nameFilter = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the account
         */
        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        /**
         * The ID of the workspace
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }


        /**
         * Number of documents to return. Defaults to the maximum which is 100
         */
        public Builder count(int count) {
            Utils.checkNotNull(count, "count");
            this.count = Optional.ofNullable(count);
            return this;
        }

        /**
         * Number of documents to return. Defaults to the maximum which is 100
         */
        public Builder count(Optional<Integer> count) {
            Utils.checkNotNull(count, "count");
            this.count = count;
            return this;
        }


        /**
         * Position of the first item in the total results. Defaults to 0
         */
        public Builder startPosition(int startPosition) {
            Utils.checkNotNull(startPosition, "startPosition");
            this.startPosition = Optional.ofNullable(startPosition);
            return this;
        }

        /**
         * Position of the first item in the total results. Defaults to 0
         */
        public Builder startPosition(Optional<Integer> startPosition) {
            Utils.checkNotNull(startPosition, "startPosition");
            this.startPosition = startPosition;
            return this;
        }


        /**
         * Filter documents where Name contains the filter. Defaults to null, to not filter
         */
        public Builder nameFilter(String nameFilter) {
            Utils.checkNotNull(nameFilter, "nameFilter");
            this.nameFilter = Optional.ofNullable(nameFilter);
            return this;
        }

        /**
         * Filter documents where Name contains the filter. Defaults to null, to not filter
         */
        public Builder nameFilter(Optional<String> nameFilter) {
            Utils.checkNotNull(nameFilter, "nameFilter");
            this.nameFilter = nameFilter;
            return this;
        }

        public GetWorkspaceDocumentsRequest build() {

            return new GetWorkspaceDocumentsRequest(
                accountId, workspaceId, count,
                startPosition, nameFilter);
        }

    }
}
