/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.models.components.WorkflowTriggerRequirementsSuccess;
import com.docusign.iam.sdk.utils.Response;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class GetWorkflowTriggerRequirementsResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Describes the requirements for triggering a workflow
     */
    private Optional<? extends WorkflowTriggerRequirementsSuccess> workflowTriggerRequirementsSuccess;

    @JsonCreator
    public GetWorkflowTriggerRequirementsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends WorkflowTriggerRequirementsSuccess> workflowTriggerRequirementsSuccess) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(workflowTriggerRequirementsSuccess, "workflowTriggerRequirementsSuccess");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.workflowTriggerRequirementsSuccess = workflowTriggerRequirementsSuccess;
    }
    
    public GetWorkflowTriggerRequirementsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Describes the requirements for triggering a workflow
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<WorkflowTriggerRequirementsSuccess> workflowTriggerRequirementsSuccess() {
        return (Optional<WorkflowTriggerRequirementsSuccess>) workflowTriggerRequirementsSuccess;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public GetWorkflowTriggerRequirementsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetWorkflowTriggerRequirementsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetWorkflowTriggerRequirementsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Describes the requirements for triggering a workflow
     */
    public GetWorkflowTriggerRequirementsResponse withWorkflowTriggerRequirementsSuccess(WorkflowTriggerRequirementsSuccess workflowTriggerRequirementsSuccess) {
        Utils.checkNotNull(workflowTriggerRequirementsSuccess, "workflowTriggerRequirementsSuccess");
        this.workflowTriggerRequirementsSuccess = Optional.ofNullable(workflowTriggerRequirementsSuccess);
        return this;
    }

    /**
     * Describes the requirements for triggering a workflow
     */
    public GetWorkflowTriggerRequirementsResponse withWorkflowTriggerRequirementsSuccess(Optional<? extends WorkflowTriggerRequirementsSuccess> workflowTriggerRequirementsSuccess) {
        Utils.checkNotNull(workflowTriggerRequirementsSuccess, "workflowTriggerRequirementsSuccess");
        this.workflowTriggerRequirementsSuccess = workflowTriggerRequirementsSuccess;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkflowTriggerRequirementsResponse other = (GetWorkflowTriggerRequirementsResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.workflowTriggerRequirementsSuccess, other.workflowTriggerRequirementsSuccess);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            workflowTriggerRequirementsSuccess);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkflowTriggerRequirementsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "workflowTriggerRequirementsSuccess", workflowTriggerRequirementsSuccess);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends WorkflowTriggerRequirementsSuccess> workflowTriggerRequirementsSuccess = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Describes the requirements for triggering a workflow
         */
        public Builder workflowTriggerRequirementsSuccess(WorkflowTriggerRequirementsSuccess workflowTriggerRequirementsSuccess) {
            Utils.checkNotNull(workflowTriggerRequirementsSuccess, "workflowTriggerRequirementsSuccess");
            this.workflowTriggerRequirementsSuccess = Optional.ofNullable(workflowTriggerRequirementsSuccess);
            return this;
        }

        /**
         * Describes the requirements for triggering a workflow
         */
        public Builder workflowTriggerRequirementsSuccess(Optional<? extends WorkflowTriggerRequirementsSuccess> workflowTriggerRequirementsSuccess) {
            Utils.checkNotNull(workflowTriggerRequirementsSuccess, "workflowTriggerRequirementsSuccess");
            this.workflowTriggerRequirementsSuccess = workflowTriggerRequirementsSuccess;
            return this;
        }
        
        public GetWorkflowTriggerRequirementsResponse build() {
            return new GetWorkflowTriggerRequirementsResponse(
                contentType,
                statusCode,
                rawResponse,
                workflowTriggerRequirementsSuccess);
        }
    }
}
