/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.utils.Response;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class GetWorkspaceDocumentContentsResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Document successfully retrieved.
     */
    private Optional<? extends InputStream> getWorkspaceDocumentContentsResponse;

    @JsonCreator
    public GetWorkspaceDocumentContentsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends InputStream> getWorkspaceDocumentContentsResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(getWorkspaceDocumentContentsResponse, "getWorkspaceDocumentContentsResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.getWorkspaceDocumentContentsResponse = getWorkspaceDocumentContentsResponse;
    }
    
    public GetWorkspaceDocumentContentsResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Document successfully retrieved.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<InputStream> getWorkspaceDocumentContentsResponse() {
        return (Optional<InputStream>) getWorkspaceDocumentContentsResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public GetWorkspaceDocumentContentsResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetWorkspaceDocumentContentsResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetWorkspaceDocumentContentsResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Document successfully retrieved.
     */
    public GetWorkspaceDocumentContentsResponse withGetWorkspaceDocumentContentsResponse(InputStream getWorkspaceDocumentContentsResponse) {
        Utils.checkNotNull(getWorkspaceDocumentContentsResponse, "getWorkspaceDocumentContentsResponse");
        this.getWorkspaceDocumentContentsResponse = Optional.ofNullable(getWorkspaceDocumentContentsResponse);
        return this;
    }


    /**
     * Document successfully retrieved.
     */
    public GetWorkspaceDocumentContentsResponse withGetWorkspaceDocumentContentsResponse(Optional<? extends InputStream> getWorkspaceDocumentContentsResponse) {
        Utils.checkNotNull(getWorkspaceDocumentContentsResponse, "getWorkspaceDocumentContentsResponse");
        this.getWorkspaceDocumentContentsResponse = getWorkspaceDocumentContentsResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceDocumentContentsResponse other = (GetWorkspaceDocumentContentsResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.getWorkspaceDocumentContentsResponse, other.getWorkspaceDocumentContentsResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            getWorkspaceDocumentContentsResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceDocumentContentsResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "getWorkspaceDocumentContentsResponse", getWorkspaceDocumentContentsResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends InputStream> getWorkspaceDocumentContentsResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * Document successfully retrieved.
         */
        public Builder getWorkspaceDocumentContentsResponse(InputStream getWorkspaceDocumentContentsResponse) {
            Utils.checkNotNull(getWorkspaceDocumentContentsResponse, "getWorkspaceDocumentContentsResponse");
            this.getWorkspaceDocumentContentsResponse = Optional.ofNullable(getWorkspaceDocumentContentsResponse);
            return this;
        }

        /**
         * Document successfully retrieved.
         */
        public Builder getWorkspaceDocumentContentsResponse(Optional<? extends InputStream> getWorkspaceDocumentContentsResponse) {
            Utils.checkNotNull(getWorkspaceDocumentContentsResponse, "getWorkspaceDocumentContentsResponse");
            this.getWorkspaceDocumentContentsResponse = getWorkspaceDocumentContentsResponse;
            return this;
        }

        public GetWorkspaceDocumentContentsResponse build() {

            return new GetWorkspaceDocumentContentsResponse(
                contentType, statusCode, rawResponse,
                getWorkspaceDocumentContentsResponse);
        }

    }
}
