/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;


public class GetWorkspaceDocumentContentsRequest {
    /**
     * The ID of the account
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;

    /**
     * The ID of the workspace
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceId")
    private String workspaceId;

    /**
     * The ID of the document
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=documentId")
    private String documentId;

    @JsonCreator
    public GetWorkspaceDocumentContentsRequest(
            String accountId,
            String workspaceId,
            String documentId) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(workspaceId, "workspaceId");
        Utils.checkNotNull(documentId, "documentId");
        this.accountId = accountId;
        this.workspaceId = workspaceId;
        this.documentId = documentId;
    }

    /**
     * The ID of the account
     */
    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    /**
     * The ID of the workspace
     */
    @JsonIgnore
    public String workspaceId() {
        return workspaceId;
    }

    /**
     * The ID of the document
     */
    @JsonIgnore
    public String documentId() {
        return documentId;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the account
     */
    public GetWorkspaceDocumentContentsRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    /**
     * The ID of the workspace
     */
    public GetWorkspaceDocumentContentsRequest withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }

    /**
     * The ID of the document
     */
    public GetWorkspaceDocumentContentsRequest withDocumentId(String documentId) {
        Utils.checkNotNull(documentId, "documentId");
        this.documentId = documentId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetWorkspaceDocumentContentsRequest other = (GetWorkspaceDocumentContentsRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.workspaceId, other.workspaceId) &&
            Utils.enhancedDeepEquals(this.documentId, other.documentId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId, workspaceId, documentId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetWorkspaceDocumentContentsRequest.class,
                "accountId", accountId,
                "workspaceId", workspaceId,
                "documentId", documentId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountId;

        private String workspaceId;

        private String documentId;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the account
         */
        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        /**
         * The ID of the workspace
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }


        /**
         * The ID of the document
         */
        public Builder documentId(String documentId) {
            Utils.checkNotNull(documentId, "documentId");
            this.documentId = documentId;
            return this;
        }

        public GetWorkspaceDocumentContentsRequest build() {

            return new GetWorkspaceDocumentContentsRequest(
                accountId, workspaceId, documentId);
        }

    }
}
