/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;

public class PauseNewWorkflowInstancesRequest {

    /**
     * The unique identifier of the account.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workflowId")
    private String workflowId;

    @JsonCreator
    public PauseNewWorkflowInstancesRequest(
            String accountId,
            String workflowId) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(workflowId, "workflowId");
        this.accountId = accountId;
        this.workflowId = workflowId;
    }

    /**
     * The unique identifier of the account.
     */
    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    @JsonIgnore
    public String workflowId() {
        return workflowId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The unique identifier of the account.
     */
    public PauseNewWorkflowInstancesRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    public PauseNewWorkflowInstancesRequest withWorkflowId(String workflowId) {
        Utils.checkNotNull(workflowId, "workflowId");
        this.workflowId = workflowId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PauseNewWorkflowInstancesRequest other = (PauseNewWorkflowInstancesRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.workflowId, other.workflowId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId,
            workflowId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PauseNewWorkflowInstancesRequest.class,
                "accountId", accountId,
                "workflowId", workflowId);
    }
    
    public final static class Builder {
 
        private String accountId;
 
        private String workflowId;
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The unique identifier of the account.
         */
        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }

        public Builder workflowId(String workflowId) {
            Utils.checkNotNull(workflowId, "workflowId");
            this.workflowId = workflowId;
            return this;
        }
        
        public PauseNewWorkflowInstancesRequest build() {
            return new PauseNewWorkflowInstancesRequest(
                accountId,
                workflowId);
        }
    }
}
