/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.models.components.UpdateWorkspaceBrandBody;
import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;


public class UpdateWorkspaceBrandRequest {
    /**
     * The ID of the account
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;

    /**
     * The ID of the workspace
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceId")
    private String workspaceId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private UpdateWorkspaceBrandBody updateWorkspaceBrandBody;

    @JsonCreator
    public UpdateWorkspaceBrandRequest(
            String accountId,
            String workspaceId,
            UpdateWorkspaceBrandBody updateWorkspaceBrandBody) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(workspaceId, "workspaceId");
        Utils.checkNotNull(updateWorkspaceBrandBody, "updateWorkspaceBrandBody");
        this.accountId = accountId;
        this.workspaceId = workspaceId;
        this.updateWorkspaceBrandBody = updateWorkspaceBrandBody;
    }

    /**
     * The ID of the account
     */
    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    /**
     * The ID of the workspace
     */
    @JsonIgnore
    public String workspaceId() {
        return workspaceId;
    }

    @JsonIgnore
    public UpdateWorkspaceBrandBody updateWorkspaceBrandBody() {
        return updateWorkspaceBrandBody;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the account
     */
    public UpdateWorkspaceBrandRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    /**
     * The ID of the workspace
     */
    public UpdateWorkspaceBrandRequest withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }

    public UpdateWorkspaceBrandRequest withUpdateWorkspaceBrandBody(UpdateWorkspaceBrandBody updateWorkspaceBrandBody) {
        Utils.checkNotNull(updateWorkspaceBrandBody, "updateWorkspaceBrandBody");
        this.updateWorkspaceBrandBody = updateWorkspaceBrandBody;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateWorkspaceBrandRequest other = (UpdateWorkspaceBrandRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.workspaceId, other.workspaceId) &&
            Utils.enhancedDeepEquals(this.updateWorkspaceBrandBody, other.updateWorkspaceBrandBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId, workspaceId, updateWorkspaceBrandBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateWorkspaceBrandRequest.class,
                "accountId", accountId,
                "workspaceId", workspaceId,
                "updateWorkspaceBrandBody", updateWorkspaceBrandBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountId;

        private String workspaceId;

        private UpdateWorkspaceBrandBody updateWorkspaceBrandBody;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the account
         */
        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        /**
         * The ID of the workspace
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }


        public Builder updateWorkspaceBrandBody(UpdateWorkspaceBrandBody updateWorkspaceBrandBody) {
            Utils.checkNotNull(updateWorkspaceBrandBody, "updateWorkspaceBrandBody");
            this.updateWorkspaceBrandBody = updateWorkspaceBrandBody;
            return this;
        }

        public UpdateWorkspaceBrandRequest build() {

            return new UpdateWorkspaceBrandRequest(
                accountId, workspaceId, updateWorkspaceBrandBody);
        }

    }
}
