/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.models.components.UpdateWorkspaceBody;
import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import java.lang.Override;
import java.lang.String;


public class UpdateWorkspaceRequest {
    /**
     * The ID of the account
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;

    /**
     * The ID of the workspace
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=workspaceId")
    private String workspaceId;


    @SpeakeasyMetadata("request:mediaType=application/json")
    private UpdateWorkspaceBody updateWorkspaceBody;

    @JsonCreator
    public UpdateWorkspaceRequest(
            String accountId,
            String workspaceId,
            UpdateWorkspaceBody updateWorkspaceBody) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(workspaceId, "workspaceId");
        Utils.checkNotNull(updateWorkspaceBody, "updateWorkspaceBody");
        this.accountId = accountId;
        this.workspaceId = workspaceId;
        this.updateWorkspaceBody = updateWorkspaceBody;
    }

    /**
     * The ID of the account
     */
    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    /**
     * The ID of the workspace
     */
    @JsonIgnore
    public String workspaceId() {
        return workspaceId;
    }

    @JsonIgnore
    public UpdateWorkspaceBody updateWorkspaceBody() {
        return updateWorkspaceBody;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The ID of the account
     */
    public UpdateWorkspaceRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    /**
     * The ID of the workspace
     */
    public UpdateWorkspaceRequest withWorkspaceId(String workspaceId) {
        Utils.checkNotNull(workspaceId, "workspaceId");
        this.workspaceId = workspaceId;
        return this;
    }

    public UpdateWorkspaceRequest withUpdateWorkspaceBody(UpdateWorkspaceBody updateWorkspaceBody) {
        Utils.checkNotNull(updateWorkspaceBody, "updateWorkspaceBody");
        this.updateWorkspaceBody = updateWorkspaceBody;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UpdateWorkspaceRequest other = (UpdateWorkspaceRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.workspaceId, other.workspaceId) &&
            Utils.enhancedDeepEquals(this.updateWorkspaceBody, other.updateWorkspaceBody);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId, workspaceId, updateWorkspaceBody);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UpdateWorkspaceRequest.class,
                "accountId", accountId,
                "workspaceId", workspaceId,
                "updateWorkspaceBody", updateWorkspaceBody);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountId;

        private String workspaceId;

        private UpdateWorkspaceBody updateWorkspaceBody;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The ID of the account
         */
        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        /**
         * The ID of the workspace
         */
        public Builder workspaceId(String workspaceId) {
            Utils.checkNotNull(workspaceId, "workspaceId");
            this.workspaceId = workspaceId;
            return this;
        }


        public Builder updateWorkspaceBody(UpdateWorkspaceBody updateWorkspaceBody) {
            Utils.checkNotNull(updateWorkspaceBody, "updateWorkspaceBody");
            this.updateWorkspaceBody = updateWorkspaceBody;
            return this;
        }

        public UpdateWorkspaceRequest build() {

            return new UpdateWorkspaceRequest(
                accountId, workspaceId, updateWorkspaceBody);
        }

    }
}
