/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.operations;

import com.docusign.iam.sdk.utils.LazySingletonValue;
import com.docusign.iam.sdk.utils.SpeakeasyMetadata;
import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import java.lang.Override;
import java.lang.String;


public class UploadCompleteBulkJobRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=accountId")
    private String accountId;


    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=jobId")
    private String jobId;

    @JsonCreator
    public UploadCompleteBulkJobRequest(
            String accountId,
            String jobId) {
        Utils.checkNotNull(accountId, "accountId");
        Utils.checkNotNull(jobId, "jobId");
        this.accountId = accountId;
        this.jobId = jobId;
    }

    @JsonIgnore
    public String accountId() {
        return accountId;
    }

    @JsonIgnore
    public String jobId() {
        return jobId;
    }

    public static Builder builder() {
        return new Builder();
    }


    public UploadCompleteBulkJobRequest withAccountId(String accountId) {
        Utils.checkNotNull(accountId, "accountId");
        this.accountId = accountId;
        return this;
    }

    public UploadCompleteBulkJobRequest withJobId(String jobId) {
        Utils.checkNotNull(jobId, "jobId");
        this.jobId = jobId;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        UploadCompleteBulkJobRequest other = (UploadCompleteBulkJobRequest) o;
        return 
            Utils.enhancedDeepEquals(this.accountId, other.accountId) &&
            Utils.enhancedDeepEquals(this.jobId, other.jobId);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            accountId, jobId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(UploadCompleteBulkJobRequest.class,
                "accountId", accountId,
                "jobId", jobId);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String accountId;

        private String jobId;

        private Builder() {
          // force use of static builder() method
        }


        public Builder accountId(String accountId) {
            Utils.checkNotNull(accountId, "accountId");
            this.accountId = accountId;
            return this;
        }


        public Builder jobId(String jobId) {
            Utils.checkNotNull(jobId, "jobId");
            this.jobId = jobId;
            return this;
        }

        public UploadCompleteBulkJobRequest build() {
            if (accountId == null) {
                accountId = _SINGLETON_VALUE_AccountId.value();
            }
            if (jobId == null) {
                jobId = _SINGLETON_VALUE_JobId.value();
            }

            return new UploadCompleteBulkJobRequest(
                accountId, jobId);
        }


        private static final LazySingletonValue<String> _SINGLETON_VALUE_AccountId =
                new LazySingletonValue<>(
                        "accountId",
                        "\"00000000-0000-0000-0000-000000000000\"",
                        new TypeReference<String>() {});

        private static final LazySingletonValue<String> _SINGLETON_VALUE_JobId =
                new LazySingletonValue<>(
                        "jobId",
                        "\"00000000-0000-0000-0000-000000000000\"",
                        new TypeReference<String>() {});
    }
}
