/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk;

import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import java.util.concurrent.TimeUnit;

import com.docusign.iam.sdk.utils.BackoffStrategy;
import com.docusign.iam.sdk.utils.HTTPClient;
import com.docusign.iam.sdk.utils.RetryConfig;
import com.docusign.iam.sdk.utils.SpeakeasyHTTPClient;
import java.lang.IllegalStateException;
import java.lang.String;
import java.lang.System;
import java.util.Optional;
import java.util.function.Consumer;


/**
 * Spring Boot Auto Configuration for iam-sdk SDK
 * This configuration class automatically configures the iam-sdk SDK
 * when Spring Boot detects it on the classpath.
 */
@AutoConfiguration
@ConditionalOnClass(IamClient.class)
@EnableConfigurationProperties(IamSDKAutoConfigProperties.class)
public class IamSDKAutoConfig {

    /**
     * Constructor.
     */
    public IamSDKAutoConfig() {
    }

    /**
     * Creates a RetryConfig bean from properties if retry is enabled.
     * 
     * @param properties the configuration properties
     * @return A configured RetryConfig instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnProperty(prefix = "iamsdk.retry-config", name = "strategy")
    public RetryConfig retryConfig(IamSDKAutoConfigProperties properties) {
        IamSDKAutoConfigProperties.RetryConfig retryProps = properties.getRetryConfig();
        
        if (RetryConfig.Strategy.BACKOFF.equals(retryProps.getStrategy())) {
            IamSDKAutoConfigProperties.RetryConfig.Backoff backoff = retryProps.getBackoff();
            return RetryConfig.builder()
                .backoff(
                    BackoffStrategy.builder()
                        .initialInterval(backoff.getInitialInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxInterval(backoff.getMaxInterval().toMillis(), TimeUnit.MILLISECONDS)
                        .maxElapsedTime(backoff.getMaxElapsedTime().toMillis(), TimeUnit.MILLISECONDS)
                        .baseFactor(backoff.getBaseFactor())
                        .jitterFactor(backoff.getJitterFactor())
                        .retryConnectError(backoff.isRetryConnectError())
                        .retryReadTimeoutError(backoff.isRetryReadTimeoutError())
                        .build()
                )
                .build();
        }
        
        // Default retry config for other strategies
        return RetryConfig.builder().build();
    }
    /**
     * Creates a {@code Consumer<String>} bean for HTTP debug logging if none exists.
     * This logger is used by the SpeakeasyHTTPClient for debug output when debug logging is enabled.
     * By default, it logs to {@code System.out}, but can be customized by providing your own {@code Consumer<String>} bean.
     *
     * @return A {@code Consumer<String>} that logs messages to {@code System.out}
     */
    @Bean
    @ConditionalOnMissingBean
    public Consumer<String> httpLogger() {
        return System.out::println;
    }
    /**
     * Creates an HTTPClient bean if none exists.
     *
     * @param properties the configuration properties
     * @param httpLogger the logger for HTTP debug output
     * @return A configured HTTPClient instance
     */
    @Bean
    @ConditionalOnMissingBean
    public HTTPClient httpClient(IamSDKAutoConfigProperties properties, Consumer<String> httpLogger) {
        IamSDKAutoConfigProperties.HttpClient httpClientProps = properties.getHttpClient();

        // Configure the static logger
        SpeakeasyHTTPClient.setLogger(httpLogger);

        if (httpClientProps != null) {
            // Configure debug logging
            SpeakeasyHTTPClient.setDebugLogging(httpClientProps.isEnableDebugLogging());

            // Configure redacted headers
            if (httpClientProps.getRedactedHeaders() != null && !httpClientProps.getRedactedHeaders().isEmpty()) {
                SpeakeasyHTTPClient.setRedactedHeaders(httpClientProps.getRedactedHeaders());
            }
        }

        return new SpeakeasyHTTPClient();
    }
    /**
     * Creates a SecuritySource bean if none exists and security properties are configured.
     *
     * @param properties the configuration properties
     * @return A configured SecuritySource instance
     */
    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnPropertyPrefix(prefix = "iamsdk.security")
    public SecuritySource securitySource(IamSDKAutoConfigProperties properties) {IamSDKAutoConfigProperties.Security securityProps = properties.getSecurity();
        com.docusign.iam.sdk.models.components.Security.Builder securityBuilder = com.docusign.iam.sdk.models.components.Security.builder();
        boolean hasAnySecurityConfiguration = false;
        // Build accessToken security from direct properties (primitive value)
        if (securityProps.getAccessToken() != null) {
            securityBuilder.accessToken(securityProps.getAccessToken());
            hasAnySecurityConfiguration = true;
        }
        
        if (!hasAnySecurityConfiguration) {
            throw new IllegalStateException("Security configuration is present but no security options are configured. " +
                "Please configure at least one security option in your application properties.");
        }
        
        return SecuritySource.of(securityBuilder.build());
    }

    /**
     * Creates the SDKConfiguration bean as the single source of truth for all SDK configuration.
     *
     * @param properties the configuration properties
     * @param httpClient the HTTP client bean
     * @param hooks the hooks bean
     * @param securitySource the security source bean (optional)
     * @param retryConfig the retry config bean (optional)
     * @return A configured SDKConfiguration instance
     */
    @Bean
    @ConditionalOnMissingBean
    public SDKConfiguration sdkConfiguration(
            IamSDKAutoConfigProperties properties,
            HTTPClient httpClient,
            com.docusign.iam.sdk.utils.Hooks hooks,
            SecuritySource securitySource,
            Optional<RetryConfig> retryConfig) {
        
        SDKConfiguration sdkConfiguration = new SDKConfiguration();
        
        sdkConfiguration.setClient(httpClient);
        
        sdkConfiguration.setHooks(hooks);
        sdkConfiguration.setSecuritySource(securitySource);
        
        if (properties.getServerUrl() != null) {
            sdkConfiguration.setServerUrl(properties.getServerUrl());
        }
        if (properties.getServer() != null) {
            sdkConfiguration.setServer(properties.getServer());
        }
        
        sdkConfiguration.setRetryConfig(retryConfig);
        
        return sdkConfiguration;
    }

    /**
     * Creates the main SDK bean using the configured SDKConfiguration.
     *
     * @param sdkConfiguration the configured SDKConfiguration bean
     * @return A configured IamClient instance
     */
    @Bean
    @ConditionalOnMissingBean
    public IamClient iamClient(SDKConfiguration sdkConfiguration) {
        return new IamClient(sdkConfiguration);
    }

    /**
     * Creates a Hooks configuration bean if none exists.
     *
     * @return A configured Hooks instance
     */
    @Bean
    @ConditionalOnMissingBean
    public com.docusign.iam.sdk.utils.Hooks hooks() {
        return new com.docusign.iam.sdk.utils.Hooks();
    }
    /**
     * Creates a Auth sub-SDK bean if none exists.
     *
     * @param iamClient the main SDK instance
     * @return A configured Auth instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Auth auth(IamClient iamClient) {
        return iamClient.auth();
    }
    /**
     * Creates a Maestro sub-SDK bean if none exists.
     *
     * @param iamClient the main SDK instance
     * @return A configured Maestro instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Maestro maestro(IamClient iamClient) {
        return iamClient.maestro();
    }
    /**
     * Creates a Navigator sub-SDK bean if none exists.
     *
     * @param iamClient the main SDK instance
     * @return A configured Navigator instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Navigator navigator(IamClient iamClient) {
        return iamClient.navigator();
    }
    /**
     * Creates a ConnectedFields sub-SDK bean if none exists.
     *
     * @param iamClient the main SDK instance
     * @return A configured ConnectedFields instance
     */
    @Bean
    @ConditionalOnMissingBean
    public ConnectedFields connectedFields(IamClient iamClient) {
        return iamClient.connectedFields();
    }
    /**
     * Creates a Workspaces1 sub-SDK bean if none exists.
     *
     * @param iamClient the main SDK instance
     * @return A configured Workspaces1 instance
     */
    @Bean
    @ConditionalOnMissingBean
    public Workspaces1 workspaces(IamClient iamClient) {
        return iamClient.workspaces();
    }
}