/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.docusign.iam.sdk.models.errors;

import com.docusign.iam.sdk.utils.Utils;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import java.io.InputStream;
import java.lang.Deprecated;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.lang.Throwable;
import java.net.http.HttpResponse;
import java.time.OffsetDateTime;
import java.util.Optional;

@SuppressWarnings("serial")
public class ErrDetails extends IamClientError {

    @Nullable
    private final Data data;

    @Nullable
    private final Throwable deserializationException;

    public ErrDetails(
                int code,
                byte[] body,
                HttpResponse<?> rawResponse,
                @Nullable Data data,
                @Nullable Throwable deserializationException) {
        super("API error occurred", code, body, rawResponse, null);
        this.data = data;
        this.deserializationException = deserializationException;
    }

    /**
    * Parse a response into an instance of ErrDetails. If deserialization of the response body fails,
    * the resulting ErrDetails instance will have a null data() value and a non-null deserializationException().
    */
    public static ErrDetails from(HttpResponse<InputStream> response) {
        try {
            byte[] bytes = Utils.extractByteArrayFromBody(response);
            Data data = Utils.mapper().readValue(bytes, Data.class);
            return new ErrDetails(response.statusCode(), bytes, response, data, null);
        } catch (Exception e) {
            return new ErrDetails(response.statusCode(), null, response, null, e);
        }
    }

    /**
     * A human-readable explanation specific to this occurrence
     */
    @Deprecated
    public Optional<String> detail() {
        return data().flatMap(Data::detail);
    }

    /**
     * A URI reference that identifies the specific occurrence
     */
    @Deprecated
    public Optional<String> instance() {
        return data().flatMap(Data::instance);
    }

    /**
     * The request path that caused the error
     */
    @Deprecated
    public Optional<String> path() {
        return data().flatMap(Data::path);
    }

    /**
     * The HTTP status code
     */
    @Deprecated
    public Optional<Long> status() {
        return data().map(Data::status);
    }

    /**
     * The timestamp when the error occurred
     */
    @Deprecated
    public Optional<OffsetDateTime> timestamp() {
        return data().flatMap(Data::timestamp);
    }

    /**
     * A short, human-readable summary of the problem
     */
    @Deprecated
    public Optional<String> title() {
        return data().map(Data::title);
    }

    /**
     * A URI reference that identifies the problem type
     */
    @Deprecated
    public Optional<String> type() {
        return data().map(Data::type);
    }

    public Optional<Data> data() {
        return Optional.ofNullable(data);
    }

    /**
     * Returns the exception if an error occurs while deserializing the response body.
     */
    public Optional<Throwable> deserializationException() {
        return Optional.ofNullable(deserializationException);
    }

    public static class Data {
        /**
         * A human-readable explanation specific to this occurrence
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("detail")
        private Optional<String> detail;

        /**
         * A URI reference that identifies the specific occurrence
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("instance")
        private Optional<String> instance;

        /**
         * The request path that caused the error
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("path")
        private Optional<String> path;

        /**
         * The HTTP status code
         */
        @JsonProperty("status")
        private long status;

        /**
         * The timestamp when the error occurred
         */
        @JsonInclude(Include.NON_ABSENT)
        @JsonProperty("timestamp")
        private Optional<OffsetDateTime> timestamp;

        /**
         * A short, human-readable summary of the problem
         */
        @JsonProperty("title")
        private String title;

        /**
         * A URI reference that identifies the problem type
         */
        @JsonProperty("type")
        private String type;

        @JsonCreator
        public Data(
                @JsonProperty("detail") Optional<String> detail,
                @JsonProperty("instance") Optional<String> instance,
                @JsonProperty("path") Optional<String> path,
                @JsonProperty("status") long status,
                @JsonProperty("timestamp") Optional<OffsetDateTime> timestamp,
                @JsonProperty("title") String title,
                @JsonProperty("type") String type) {
            Utils.checkNotNull(detail, "detail");
            Utils.checkNotNull(instance, "instance");
            Utils.checkNotNull(path, "path");
            Utils.checkNotNull(status, "status");
            Utils.checkNotNull(timestamp, "timestamp");
            Utils.checkNotNull(title, "title");
            Utils.checkNotNull(type, "type");
            this.detail = detail;
            this.instance = instance;
            this.path = path;
            this.status = status;
            this.timestamp = timestamp;
            this.title = title;
            this.type = type;
        }
        
        public Data(
                long status,
                String title,
                String type) {
            this(Optional.empty(), Optional.empty(), Optional.empty(),
                status, Optional.empty(), title,
                type);
        }

        /**
         * A human-readable explanation specific to this occurrence
         */
        @JsonIgnore
        public Optional<String> detail() {
            return detail;
        }

        /**
         * A URI reference that identifies the specific occurrence
         */
        @JsonIgnore
        public Optional<String> instance() {
            return instance;
        }

        /**
         * The request path that caused the error
         */
        @JsonIgnore
        public Optional<String> path() {
            return path;
        }

        /**
         * The HTTP status code
         */
        @JsonIgnore
        public long status() {
            return status;
        }

        /**
         * The timestamp when the error occurred
         */
        @JsonIgnore
        public Optional<OffsetDateTime> timestamp() {
            return timestamp;
        }

        /**
         * A short, human-readable summary of the problem
         */
        @JsonIgnore
        public String title() {
            return title;
        }

        /**
         * A URI reference that identifies the problem type
         */
        @JsonIgnore
        public String type() {
            return type;
        }

        public static Builder builder() {
            return new Builder();
        }


        /**
         * A human-readable explanation specific to this occurrence
         */
        public Data withDetail(String detail) {
            Utils.checkNotNull(detail, "detail");
            this.detail = Optional.ofNullable(detail);
            return this;
        }


        /**
         * A human-readable explanation specific to this occurrence
         */
        public Data withDetail(Optional<String> detail) {
            Utils.checkNotNull(detail, "detail");
            this.detail = detail;
            return this;
        }

        /**
         * A URI reference that identifies the specific occurrence
         */
        public Data withInstance(String instance) {
            Utils.checkNotNull(instance, "instance");
            this.instance = Optional.ofNullable(instance);
            return this;
        }


        /**
         * A URI reference that identifies the specific occurrence
         */
        public Data withInstance(Optional<String> instance) {
            Utils.checkNotNull(instance, "instance");
            this.instance = instance;
            return this;
        }

        /**
         * The request path that caused the error
         */
        public Data withPath(String path) {
            Utils.checkNotNull(path, "path");
            this.path = Optional.ofNullable(path);
            return this;
        }


        /**
         * The request path that caused the error
         */
        public Data withPath(Optional<String> path) {
            Utils.checkNotNull(path, "path");
            this.path = path;
            return this;
        }

        /**
         * The HTTP status code
         */
        public Data withStatus(long status) {
            Utils.checkNotNull(status, "status");
            this.status = status;
            return this;
        }

        /**
         * The timestamp when the error occurred
         */
        public Data withTimestamp(OffsetDateTime timestamp) {
            Utils.checkNotNull(timestamp, "timestamp");
            this.timestamp = Optional.ofNullable(timestamp);
            return this;
        }


        /**
         * The timestamp when the error occurred
         */
        public Data withTimestamp(Optional<OffsetDateTime> timestamp) {
            Utils.checkNotNull(timestamp, "timestamp");
            this.timestamp = timestamp;
            return this;
        }

        /**
         * A short, human-readable summary of the problem
         */
        public Data withTitle(String title) {
            Utils.checkNotNull(title, "title");
            this.title = title;
            return this;
        }

        /**
         * A URI reference that identifies the problem type
         */
        public Data withType(String type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        @Override
        public boolean equals(java.lang.Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            Data other = (Data) o;
            return 
                Utils.enhancedDeepEquals(this.detail, other.detail) &&
                Utils.enhancedDeepEquals(this.instance, other.instance) &&
                Utils.enhancedDeepEquals(this.path, other.path) &&
                Utils.enhancedDeepEquals(this.status, other.status) &&
                Utils.enhancedDeepEquals(this.timestamp, other.timestamp) &&
                Utils.enhancedDeepEquals(this.title, other.title) &&
                Utils.enhancedDeepEquals(this.type, other.type);
        }
        
        @Override
        public int hashCode() {
            return Utils.enhancedHash(
                detail, instance, path,
                status, timestamp, title,
                type);
        }
        
        @Override
        public String toString() {
            return Utils.toString(Data.class,
                    "detail", detail,
                    "instance", instance,
                    "path", path,
                    "status", status,
                    "timestamp", timestamp,
                    "title", title,
                    "type", type);
        }

        @SuppressWarnings("UnusedReturnValue")
        public final static class Builder {

            private Optional<String> detail = Optional.empty();

            private Optional<String> instance = Optional.empty();

            private Optional<String> path = Optional.empty();

            private Long status;

            private Optional<OffsetDateTime> timestamp = Optional.empty();

            private String title;

            private String type;

            private Builder() {
              // force use of static builder() method
            }


            /**
             * A human-readable explanation specific to this occurrence
             */
            public Builder detail(String detail) {
                Utils.checkNotNull(detail, "detail");
                this.detail = Optional.ofNullable(detail);
                return this;
            }

            /**
             * A human-readable explanation specific to this occurrence
             */
            public Builder detail(Optional<String> detail) {
                Utils.checkNotNull(detail, "detail");
                this.detail = detail;
                return this;
            }


            /**
             * A URI reference that identifies the specific occurrence
             */
            public Builder instance(String instance) {
                Utils.checkNotNull(instance, "instance");
                this.instance = Optional.ofNullable(instance);
                return this;
            }

            /**
             * A URI reference that identifies the specific occurrence
             */
            public Builder instance(Optional<String> instance) {
                Utils.checkNotNull(instance, "instance");
                this.instance = instance;
                return this;
            }


            /**
             * The request path that caused the error
             */
            public Builder path(String path) {
                Utils.checkNotNull(path, "path");
                this.path = Optional.ofNullable(path);
                return this;
            }

            /**
             * The request path that caused the error
             */
            public Builder path(Optional<String> path) {
                Utils.checkNotNull(path, "path");
                this.path = path;
                return this;
            }


            /**
             * The HTTP status code
             */
            public Builder status(long status) {
                Utils.checkNotNull(status, "status");
                this.status = status;
                return this;
            }


            /**
             * The timestamp when the error occurred
             */
            public Builder timestamp(OffsetDateTime timestamp) {
                Utils.checkNotNull(timestamp, "timestamp");
                this.timestamp = Optional.ofNullable(timestamp);
                return this;
            }

            /**
             * The timestamp when the error occurred
             */
            public Builder timestamp(Optional<OffsetDateTime> timestamp) {
                Utils.checkNotNull(timestamp, "timestamp");
                this.timestamp = timestamp;
                return this;
            }


            /**
             * A short, human-readable summary of the problem
             */
            public Builder title(String title) {
                Utils.checkNotNull(title, "title");
                this.title = title;
                return this;
            }


            /**
             * A URI reference that identifies the problem type
             */
            public Builder type(String type) {
                Utils.checkNotNull(type, "type");
                this.type = type;
                return this;
            }

            public Data build() {

                return new Data(
                    detail, instance, path,
                    status, timestamp, title,
                    type);
            }

        }
    }

}

